INSERT INTO QUESTIONNAIRE (IDQUESTIONNAIRE,IDINSURANCE, NAMEQUESTIONNAIRE, DESCRIPTION, CREATEDAT, STATUS, SOURCEFILE, TOTALQUESTION) VALUES ('2','1','CUESTIONARIO CRIME 2024 ','CUESTIONARIO CRIME 2024 BASE','','TRUE','CUESTIONARIOCRIME2024.docx', 250);

INSERT INTO QUESTION (IDQUESTION,IDQUESTIONNAIRE,TYPEQUESTION, DESCRIPTIONQUESTION ,QUESTIONTEXT ,QUESTIONJSON ,PARENTID ,DOCUMENTID) VALUES
                                                                                                                                          (2001,'2','DES','SECTION A - PARTICULARS OF PROPOSER / SECCION A - CARACTERISTICAS DEL PROPONENTE','','','',''),
                                                                                                                                          (2002,'2','NORMAL','1','Razon social del proponente incluyendo todas las Empresas Bancarias en las cuales el Proponente tiene una participación que le confiere control de la gesióny para las cuales se desea cobertura - Title of the Proposer including all subsidiary Companies in which the Proposer has a controlling interest and for which cover is required.','','','crime1'),
                                                                                                                                          (2003,'2','NORMAL','2','Dirección Principal - Principal Address of the Proposer','','','crime2'),
                                                                                                                                          (2004,'2','NORMAL','3','When Established - Fecha de constitución','','','crime3'),

                                                                                                                                          (2005,'2','DES','4','These should be as shown in the last Annual Statement / Report and Accounts PLEASE ENCLOSE A COPY - Las cifras deberán corresponder al último Balance o Memoria Anual.  POR FAVOR ADJUNTAR COPIA','','',''),
                                                                                                                                          (2006,'2','SUB','a','Authorised Capital - Capital Social','','2005','crime4a'),
                                                                                                                                          (2007,'2','SUB','b','Paid up Capital -  Capital Desembolsado','','2005','crime4b'),
                                                                                                                                          (2008,'2','SUB','c','Total Assets - Total Activos','','2005','crime4c'),
                                                                                                                                          (2009,'2','SUB','d','Total Deposit - Total Depósitos','','2005','crime4d'),
                                                                                                                                          (2010,'2','SUB','e','Total Loans and Discounts:-Total Préstamos y Descuentos','','2005','crime4e'),
                                                                                                                                          (2011,'2','DES','','These should be as shown in the last Annual Statement / Report and Accounts PLEASE ENCLOSE A COPY -These should be as shown in the last Annual Statement / Report and Accounts PLEASE ENCLOSE A COPY','','',''),


                                                                                                                                          (2012,'2','DES','5','What approximate percentage of the Proposers total revenues are derived from the following operations: - Que porcentage de los ingresos del Proponente se derivan de las siguientes actividades?:','','',''),
                                                                                                                                          (2013,'2','SUB','a','Comercial Banking','{"5AR1":{"id": "5AR1","text":"","code":"crime5ar1"}}','2012',''),
                                                                                                                                          (2014,'2','SUB','b','TrustOperations','{"5BR1":{"id": "5BR1","text":"","code":"crime5br1"}}','2012',''),
                                                                                                                                          (2015,'2','SUB','c','Retail Banking','{"5CR1":{"id": "5CR1","text":"","code":"crime5cr1"}}','2012',''),
                                                                                                                                          (2016,'2','SUB','d','Stock Brokerage Transactions','{"5DR1":{"id": "5DR1","text":"","code":"crime5dr1"}}','2012',''),
                                                                                                                                          (2017,'2','SUB','e','Foreign Exchange Dealings','{"5ER1":{"id": "5ER1","text":"","code":"crime5er1"}}','2012',''),
                                                                                                                                          (2018,'2','SUB','f','Investment Banking','{"5FR1":{"id": "5FR1","text":"","code":"crime5fr1"}}','2012',''),

                                                                                                                                          (2019,'2','SUB','i','Fund Management','{"5FR1A1":{"id": "5FR1A1","text":"","code":"crime5fr1a1"}}','2018',''),
                                                                                                                                          (2020,'2','SUB','ii','Venture Capital','{"5FR1A2":{"id": "5FR1A2","text":"","code":"crime5fr1a2"}}','2018',''),
                                                                                                                                          (2021,'2','SUB','iii','Overseas Advisory','{"5FR1A3":{"id": "5FR1A3","text":"","code":"crime5fr1a3"}}','2018',''),
                                                                                                                                          (2022,'2','SUB','iv','Merger and Acquisition advice','{"5FR1A4":{"id": "5FR1A4","text":"","code":"crime5fr1a4"}}','2018',''),
                                                                                                                                          (2023,'2','SUB','v','Share Placing and New Issues','{"5FR1A5":{"id": "5FR1A5","text":"","code":"crime5fr1a5"}}','2018',''),

                                                                                                                                          (2024,'2','SUB','g','Leasing','{"5GR1":{"id": "5GR1","text":"","code":"crime5gr1"}}','2012',''),
                                                                                                                                          (2025,'2','SUB','h','Factoring','{"5HR1":{"id": "5HR1","text":"","code":"crime5hr1"}}','2012',''),
                                                                                                                                          (2026,'2','SUB','i','Others (Please Specify) Por favor aclarar ','{"5IR1":{"id": "5IR1","text":"","code":"crime5ir1"}}','2012',''),

                                                                                                                                          (2027,'2','DES','6','State Number and Value of: - Indicar el número y valor de','','',''),
                                                                                                                                          (2028,'2','SUB','a','Current cheque accounts - Cuentas corrientes','{"6AR1":{"id": "6AR1","text":"NUMBER / NÚMERO","code":"crime6ar1"},"6AR2":{"id": "6AR2","text":"VALUE / VALOR","code":"crime6ar2"}}','2027',''),
                                                                                                                                          (2029,'2','SUB','b','Inactive/dormant accounts (being those with no movements in or out during the past 12 months) Cuentas inactivas (las que no hayan tenido movimientos durante los pasados 12 meses)','{"6BR1":{"id": "6BR1","text":"NUMBER / NÚMERO","code":"crime6br1"},"6BR2":{"id": "6BR2","text":"VALUE / VALOR","code":"crime6br2"}}','2027',''),
                                                                                                                                          (2030,'2','SUB','c','Savings and deposit accounts - Cuentas de Ahorros y Depositos','{"6CR1":{"id": "6CR1","text":"NUMBER / NÚMERO","code":"crime6cr1"},"6CR2":{"id": "6CR2","text":"VALUE / VALOR","code":"crime6cr2"}}','2027',''),

                                                                                                                                          (2031,'2','DES','SECTION B - STAFF AND LOCATIONS / SECCION B – PERSONAL Y UBICACIONES','','','',''),

                                                                                                                                          (2032,'2','NORMAL','1','State the number of Directors (Salaried and Permanent only) - Indicar el número de Directores (solo asalariados y fijos)','','2031','crimes2p1'),
                                                                                                                                          (2033,'2','DES','2','State the numbers falling in each of the following categories:-Indicar el número que corresponde a cada una de las siguientes categorias','','2031',''),
                                                                                                                                          (2034,'2','SUB','a','Number of locations-Número de oficinas/sucursales/Ubicaciones','{"S2P2AR1":{"id":"S2P2AR1","text":"Head Office-Casa Matriz","code":"crimes2p2ar1"},"S2P2AR2":{"id": "S2P2AR2","text":"Computer Centre / Administraction-Centre Centro informático / administración","code":"crimes2p2ar2"},"S2P2AR3":{"id":"S2P2AR3","text":"Main Branches-Sucursales Principales","code":"crimes2p2ar3"},"S2P2AR4":{"id": "S2P2AR4","text":"Other Locations-Otros Locales","code":"crimes2p2ar4"},"S2P2AR5":{"id":"S2P2AR5","text":"Subsidiaries-Subsidiarias","code":"crimes2p2ar5"}}','2033',''),
                                                                                                                                          (2035,'2','SUB','b','Number of Employees (i) Banking and Officers (who are Duties not Directors): (Class I)-Número de Empleados y (i)	Tareas Oficiales Jerarquicos Bancarias(que no son directores),(Clase I)','{"S2P2BR1":{"id":"S2P2BR1","text":"Head Office-Casa Matriz","code":"crimes2p2b1r1"},"S2P2B1R2":{"id":"S2P2B1R2","text":"Main Branches-Sucursales Principales","code":"crimes2p2b1r2"},"S2P2B1R3":{"id":"S2P2B1R3","text":"Other Locations-Otros Locales","code":"crimes2p2b1r3"},"S2P2B1R4":{"id": "S2P2B1R4","text":"Subsidiaries-Subsidiarias","code":"crimes2p2b1r4"}}','2033',''),
                                                                                                                                          (2036,'2','SUB','','Employees of all grades (ii) Non Including messengers,Banking guards, domestic employees 	Duties and the like (Class II&III) - Incluyendo empleados de (ii) Tareas cualquier Categoria incluso Extra mensajeros, guardias de 	Bancarias seguridad,Empleados de,(Clase II y III)limpieza, etc.','{"S2P2B2R1":{"id":"S2P2B2R1","text":"Head Office-Casa Matriz","code":"crimes2p2b2r1"},"S2P2B2R2":{"id": "S2P2B2R2","text":"Computer Centre / Administraction-Centre Centro informático / administración","code":"crimes2p2b2r2"},"S2P2B2R3":{"id":"S2P2B2R3","text":"Main Branches-Sucursales Principales","code":"crimes2p2b2r3"},"S2P2B2R4":{"id": "S2P2B2R4","text":"Other Locations-Otros Locales","code":"crimes2p2b2r4"},"S2P2B2R5":{"id":"S2P2B2R5","text":"Subsidiaries-Subsidiarias","code":"crimes2p2b2r5"}}','2035',''),
                                                                                                                                          (2037,'2','SUB','c','Number of Automated Teller Machines (Including under (Off Premises) those that are not located at your own property):-Número de cajeros automaticos (incluyendo bajo (Remotos) aquellos que no se encuentren ubicados en sus propios locales/sucursales/oficinas)','{"S2P2CR1":{"id":"S2P2CR1","text":"Head Office-Casa Matriz","code":"crimes2p2cr1"},"S2P2CR2":{"id": "S2P2CR2","text":"Computer Centre / Administraction-Centre Centro informático / administración","code":"Off Premises-Remotos"},"S2P2CR3":{"id":"S2P2CR3","text":"Main Branches-Sucursales Principales","code":"crimes2p2cr3"},"S2P2CR4":{"id": "S2P2CR4","text":"Other Locations-Otros Locales","code":"crimes2p2cr4"},"S2P2CR5":{"id":"S2P2CR5","text":"Subsidiaries-Subsidiarias","code":"crimes2p2cr5"}}','2033',''),
                                                                                                                                          (2038,'2','SUB','d','Please state maximum number of ATMs at any one location:- Por favor indicar el número máximo de cajeros automaticos en un local:','{"S2P2DR1":{"id":"S2P2DR1","text":"Head Office-Casa Matriz","code":"crimes2p2dr1"},"S2P2DR2":{"id": "S2P2DR2","text":"Computer Centre / Administraction-Centre Centro informático / administración","code":"crimes2p2dr2"},"S2P2DR3":{"id":"S2P2DR3","text":"Main Branches-Sucursales Principales","code":"crimes2p2dr3"},"S2P2DR4":{"id": "S2P2DR4","text":"Other Locations-Otros Locales","code":"crimes2p2dr4"},"S2P2DR5":{"id":"S2P2DR5","text":"Subsidiaries-Subsidiarias","code":"crimes2p2dr5"}}','2033',''),


                                                                                                                                          (2039,'2','DES','SECTION C – PARTICULARS OF COVERAGE / CARACTERISTICAS DE LA COBERTURA','','','',''),
                                                                                                                                          (2041,'2','NORMAL','1','State the LIMIT OF INDEMNITY required for  COMPREHENSIVE CRIME POLICY-Indicar el LIMITE DE INDEMNIZACION requerido para la POLIZA DE CRIMEN INTEGRAL','','2039','crimes3p1'),
                                                                                                                                          (2042,'2','DES','2','Have you in existence any COMPREHENSIVE CRIME POLICY such as? - Tiene en vigencia alguna póliza de seguro de CRIMEN INTEGRAL tal como?','','2039',''),
                                                                                                                                          (2043,'2','OPTIONAL','a','Bankers Blanket Bond','{"S2P2A":{"id":"S2P2A","text":"", "code":"crimes2p2a"}}','2042',''),
                                                                                                                                          (2044,'2','OPTIONAL','b','Electronic & Computer Crime','{"S2P2B":{"id": "S2P2B","text":"Electronic & Computer Crime", "code":"crimes2p2b"}}','2042',''),
                                                                                                                                          (2045,'2','OPTIONAL','c','Professional Indemnity','{"S2P2C":{"id":"S2P2C","text":"Professional Indemnity", "code":"crimes2p2c"}}','2042',''),
                                                                                                                                          (2046,'2','OPTIONAL','d','Directors and Officers Liability','{"S2P2D":{"id": "S2P2D","text":"Directors and Officers Liability", "code":"crimes2p2d"}}','2042',''),
                                                                                                                                          (2047,'2','DES','2.1','If so, state amount / with whom arranged (Insurer) - En caso afirmativo, indicar la suma asegurada y el nombre de la Compañía Aseguradora','','2042',''),
                                                                                                                                          (2048,'2','SUB','a','Sum Insured / Suma Asegurada: ','{"S2P2F":{"id":"S2P2F","text":"","code":"crimes2p2f"}}','2047',''),
                                                                                                                                          (2049,'2','SUB','b','Insurer / Compania Aseguradora: ','{"S2P2G":{"id":"S2P2G","text":"", "code":"crimes2p2g"}}','2047',''),
                                                                                                                                          (2050,'2','OPTIONAL','3','Has any proposal for insurance of this nature been declined by any Insurer or has any policy been cancelled or renewal thereof refused?-Le ha sido rechazada alguna propuesta de seguro de esta indole por alguna Aseguradora o le ha sido cancelada alguna póliza o denegada su renovacion?','{"S2P3A":{ "id":"SEP3A","text":"","code":"crimes2p3a"}}','2039',''),
                                                                                                                                          (2051,'2','NORMAL','3.1','If so, give the reasons stated-En caso afirmativo, indicar las razones','','2050','crimes2p3b');


INSERT INTO QUESTION (IDQUESTION,IDQUESTIONNAIRE,TYPEQUESTION, DESCRIPTIONQUESTION ,QUESTIONTEXT ,QUESTIONJSON ,PARENTID ,DOCUMENTID) VALUES
                                                                                                                                          (2052,'2','DES','SECTION D - VALUES AT RISK / SECTION D - VALORES EN RIESGO','','','',''),
                                                                                                                                          (2053,'2','DES','1','Please state the maximum value of securities (including negotiable collateral, un-issued stock certificates etc) (please indicate currency):-Indicar sumas máximos de valores (incluye certificados de acciones no emitidos , valores negociables) (Por favor indicar moneda):-SECURITIES ON PREMISES / VALORES DENTRO DE SUS LOCALES - (Please indicate currency - Por favor indicar moneda)','','2052',''),
                                                                                                                                          (2054,'2','NORMAL','a','at HEAD OFFICE (en la casa matriz):','{"S4P1A":{ "id":"S4P1A","text":"", "code":"crimes4p1a"}}','2053','crimes4p1a'),
                                                                                                                                          (2055,'2','NORMAL','b','at MAIN BRANCHES (Sucursales Principales):','{"S4P1B":{ "id":"S4P1B","text":"","code":"crimes4p1b"}}','2053','crimes4p1b'),
                                                                                                                                          (2056,'2','NORMAL','c','at OTHER LOCATIONS (en otros locales):','{"S4P1C":{ "id":"S4P1C","text":"","code":"crimes4p1c"}}','2053','crimes4p1c'),
                                                                                                                                          (2057,'2','NORMAL','d','with CUSTODIANS (con ente custodio(s)):','{"S4P1D":{ "id":"S4P1D","text":"","code":"crimes4p1d"}}','2053','crimes4p1d'),

                                                                                                                                          (2058,'2','DES','2','Please state maximum amount of cash including stock of un-issued travellers cheques bullion or similar (please indicate currency):-Indicar importe máximo de efectivo incuyendo cheques de viajero sin emitir, lingotes y valores similares (Por favor indicar moneda):-CASH ON PREMISES / EFECTIVO DENTRO DE SUS LOCALES (Please indicate currency - Por favor indicar moneda)','','2052',''),
                                                                                                                                          (2059,'2','SUB','a','at HEAD OFFICE (en la casa matriz):','{"S4P2A":{ "id":"S4P2A","text":"","code":"crimes4p2a"}}','2058',''),
                                                                                                                                          (2060,'2','SUB','b','at MAIN BRANCHES (Sucursales Principales):','{"S4P2B":{ "id":"S4P2B","text":"","code":"crimes4p2b"}}','2058',''),
                                                                                                                                          (2061,'2','SUB','c','at OTHER LOCATIONS (en otros locales):','{"S4P2C":{ "id":"S4P2C","text":"","code":"crimes4p2c"}}','2058',''),
                                                                                                                                          (2062,'2','SUB','d','at INDIVIDUAL TELLERS (en cajeros individuales)','{"S4P2D":{ "id":"S4P2D","text":"","code":"crimes4p2d"}}','2058',''),
                                                                                                                                          (2063,'2','SUB','e','at the ENTIRE COUNTER excluding "drop safes"(en la totalidad de las cajas de ventanilla excluyendo "drop safes")','{"S4P2E":{ "id":"S4P2E","text":"","code":"crimes4p2e"}}','2058',''),
                                                                                                                                          (2064,'2','SUB','f','within AUTOMATED TELLER MACHINES (en cajeros automáticos):','{"S4P2F":{ "id":"S4P2F","text":"","code":"crimes4p2f"}}','2058',''),
                                                                                                                                          (2065,'2','SUB','g','with CUSTODIANS (en custodios):','{"S4P2G":{ "id":"S4P2G","text":"","code":"crimes4p2g"}}','2058',''),

                                                                                                                                          (2066,'2','DES','3','Please state the maximum values (please indicate currency) carried by: Indicar importe máximo (Por favor indicar moneda) transportado por:','','2052',''),
                                                                                                                                          (2067,'2','DES','','TRANSIT / TRANSLADOS CASH / EFECTIVO (please indicate currency Por favor indicar moneda) - TRANSIT / TRANSLADOS CASH / EFECTIVO (please indicate currency Por favor indicar moneda)','','2066',''),
                                                                                                                                          (2068,'2','SUB','a','ASSUREDS own Armoured Motor Vehicle-Vehículos Blindados propios del banco','{"S4P3AR1":{"Id":"S4P3AR1", "text":"","code":"crimes4p3ar1"}}','2066',''),
                                                                                                                                          (2069,'2','SUB','b','ASSUREDS own NON Armoured Vehicle-Vehículos NO-Blindados propios del banco','{"S4P3BR1":{"Id":"S4P3BR1", "text":"","code":"crimes4p3br1"}}','2066',''),
                                                                                                                                          (2070,'2','SUB','c','THIRD PARTY Armoured Motor Vehicles-Vehículos Blindados de Terceros','{"S4P3CR1":{"Id":"S4P3CR1", "text":"","code":"crimes4p3cr1"}}','2066',''),
                                                                                                                                          (2071,'2','SUB','d','MESSENGERS-Mensajeros','{"S4P3DR1":{"Id":"S4P3DR1", "text":"crimes4p3dr1"},"S4P3DR2":{"Id":"S4P3DR2", "text":"","code":"crimes4p3dr2"}}','2066',''),

                                                                                                                                          (2072,'2','SUB','4','If Third Party Armoured Vehicles are used, please state NAME OF COMPANY:-Si se usa Vehículos Blindados de Terceros, Por favor nombrar la comania','','2052','crimes4p4'),

                                                                                                                                          (2073,'2','DES','SECTION E – CLAIM EXPERIENCE / SECCION E – EXPERIENCIA SINIESTRAL','','','',''),
                                                                                                                                          (2074,'2','TABLE','1','Please give brief details, of any loss(es), (whether insured or uninsured), discovered by the Proposer or any of its Responsible Officers who are responsible for discovery of a loss, sustained during the past FIVE (5) YEARS:-- (Include Bankers Blanket Bond AND Computer Crime losses)-Indicar a continuación, brevemente, cualquier pérdida(s) (aseguradas o no) que haya sufrido el Proponente, sufrida durante los ultimos CINCO (5) AÑOS: (Incluyendo Póliza Integral Bancaria Y Delitos Informaticos).','{"S5P1AR1":{"Id":"S5P1$AR1", "text":"Date Of Discovery-Fecha de Descubrimiento","code":"crimes5p1$ar1"},"S5P1AR2":{"Id":"S5P1$AR2", "text":"Nature O Loss-Naturaleza de la pérdida","code":"crimes5p1$ar2"},"S5P1AR3":{"Id":"S5P1$AR3", "text":"Location-Oficina","code":"crimes5p1$ar3"},"S5P1AR4":{"Id":"S5P1$AR4", "text":"Amount of Loss - BEFORE the application of any deductible/Cantidad - ANTES de la aplicación de cualquier franquicia","code":"crimes5p1$ar4"}}','',''),

                                                                                                                                          (2075,'2','OPTIONAL-NORMAL','2a','Does the Proposer, or any of its Responsible Officers who are responsible for discovery of a loss have any knowledge of any act, omission, fact, event or circumstance which might give rise to a loss under this proposed insurance?-El Proponente, despues de una investigación completa, o cualquier de sus directores, oficiales, socios o fideicomisarios, tiene algun conocimiento de cualquier acto, omision, hecho, evento o circumstancia que pueda dar cabo a una pérdida bajo el seguro propuesto?, If "yes", please provide full details on a separate sheet-En caso afirmativo, Por favor proporcionar todos los detalles en otra hoja','{"S5P2A":{"Id":"S5P2A", "text":"","code":"crimes5p2a"}}','',''),

                                                                                                                                          (2076,'2','OPTIONAL-NORMAL','3a','In the event that a loss has been discovered, has the Proposer taken remedial action to prevent or avoid recurrence? - En caso de descubrimento de una pérdida, el Proponente ha tomado acciones para remediar, impedir o evitar su repetición? - If "yes", please provide full details on a separate sheet - En caso afirmativo, Por favor proporcionar todos los detalles en otra hoja','{"S5P3A":{"Id":"S5P3A", "text":"","code":"crimes5p3a"}}','',''),

                                                                                                                                          (2077,'2','OPTIONAL-NORMAL','4a','During the past five (5) years, has the proposer been the subject of an insurance survey carried out on behalf Comprehensive Crime insurers?-En los últimos cinco (5) años, ha sido el proponiente sujeto a una inspección de seguro llevado a cabo en nombre de aseguradores de pólizas de Crimen integral?,If yes, has the proposer carried out all the recommendations of such survey?-En caso afirmativo, han sido todas las recomendaciones implementadas por el proponente?','{"S5P4A":{"Id":"S5P4A", "text":"","code":"crimes5p4a"}}','',''),

                                                                                                                                          (2078,'2','DES','SECTION F – INTERNAL CONTROLS AND PROCEDURES, AUDIT AND COMPLIANCE / CONTROLES Y PROCEDIMIENTOS INTERNOS, AUDITORIA Y SEGUIMIENTO','','','',''),
                                                                                                                                          (2079,'2','OPTIONAL','1a','Have you a RULE BOOK or BOOKS or WRITTEN INSTRUCTIONS or MANUAL covering all aspects of your business which will be maintained and operated and which clearly define the duties of each Employee?-Tienen algún REGLAMENTOS(S) o INSTRUCCIONES ESCRITAS o MANUAL que contemple todos los aspectos de su actividad y que definan claramente las tareas de cada empleado, manteniendolos actualizados y en uso?','{"S6P1A":{"Id":"S6P1A", "text":"","code":"crimes6p1A"}}','2078',''),
                                                                                                                                          (2080,'2','OPTIONAL','1b','Is the attention of each Employee drawn to these instructions and to their duty of compliance therewith?-Cononoce y se llama la atención a cada empleado sobre tales instrucciónes y su deber de cumplir con ellas?','{"S6P1B":{"Id":"S6P1B", "text":"","code":"crimes6p1b"}}','2078',''),
                                                                                                                                          (2081,'2','OPTIONAL','1c','Are the duties of each Employee arranged so that no one Employee is permitted to control any transaction from commencement to completion.-Están ordenadas los deberes de los empleados de modo que no se les permita a ninguno de ellos el control de una transacción desde su comienzo hasta su terminación?','{"S6P1C":{"Id":"S6P1C", "text":"","code":"crimes6p1c"}}','2078',''),

                                                                                                                                          (2082,'2','NORMAL','2','Are Employees trained (and re-trained from time to time) in security procedures including electronic data security?-Se entrena a los Empleados ( y se re-entrenan periódicamente) en procedimientos de seguridad incluyendo seguridad de datos electrónicos?','','2078','crimes6p2'),

                                                                                                                                          (2083,'2','OPTIONAL','3a','Are unannounced and irregular changes made in the position of Employees within a particular job strata?-Se hacen cambios a intervalos irregulares y sin previo aviso en las tareas de empleados de una misma categoria?','{"S6P3A":{"Id":"S6P3A", "text":"", "code":"crimes6p3a"}}','2078',''),
                                                                                                                                          (2084,'2','OPTIONAL','3b','Are all Employees required to take an uninterrupted holiday of at least two weeks in each calendar year during which they perform no duties and are required to stay away from the Bank premises?-Están todos los empleados obligados a tomar vacaciones ininterrumpidas de por lo menos, dos semanas al año, durante las cuales no realizan tarea alguna ni concurren a ninguno de los locales del Banco?','{"S6P3B":{"Id":"S6P3B","text":"", "code":"crimes6p3b"}}','2078',''),
                                                                                                                                          (2085,'2','OPTIONAL','3c','Are there established staff recruitment and leaving procedures?-Tienen establezido procedimientos para reclutamiento y cesamiento de empleados?','{"S6P3C":{"Id":"S6P3C","text":"", "code":"crimes6p3c"}}','2078',''),

                                                                                                                                          (2086,'2','OPTIONAL','4a','Is joint custody* established and maintained for the safeguarding of: - Se ha establecido y se mantiene custodia conjunta* para la protección de:','{"S6P4A":{"Id":"S6P4A", "text":"","code":"crimes6p4a"}}','2078',''),
                                                                                                                                          (2087,'2','OPTIONAL','i','Access to Property while in safes or vaults?-Acceso a los Bienes en caja fuertas o camaras acorazadas?','{"S6P4A1":{"Id":"S6P4A1","text":"", "code":"crimes6p4a1"}}','2086',''),
                                                                                                                                          (2088,'2','OPTIONAL','ii','All keys to safes and vaults-Las llaves de las cajas fuertes y camaras acorazadas?','{"S6P4A2":{"Id":"S6P4A2", "text":"","code":"crimes6p4a2"}}','2086',''),
                                                                                                                                          (2089,'2','OPTIONAL','iii','Access Codes, cyphers and test keys?-Los códigos de acceso, cifras, claves y llaves maestras?','{"S6P4A3":{"Id":"S6P4A3","text":"", "code":"crimes6p4a3"}}','2086',''),
                                                                                                                                          (2090,'2','DES','','"Joint Custody" is understood as the handling in the presence of, and under the observation of at least one other person, said person being equally accountable for the physical protection and safeguarding of the various items or records involved.-Se entiende por "Custodia Conjunta" el manejo en presencia o bajo la observación de por lo menos una persona más, la cual será igualmente responsible de la protección física y salvaguardia de los diversos objetos o registros en cuestion.','','2078',''),
                                                                                                                                          (2091,'2','DES','b','Is dual control** established and maintained for the handling of:-Se ha establecido y se mantiene un control doble** para el manejo de:','','2078',''),
                                                                                                                                          (2092,'2','OPTIONAL','i','All types of securities, negotiable and non-negotiable instruments and un-issued blank forms of said items?-Todo tipo de títulos y acciones, documentos negociables o no, asi como formularios de los mismos, no emitidos y en blanco?','{"S6P4B1":{"Id":"S6P4B1","text":"", "code":"crimes6p4b1"}}','2091',''),
                                                                                                                                          (2093,'2','OPTIONAL','ii','The reserve supply of official cheques, drafts and un-issued travellers cheques?-El Stock de la reserva de cheques oficiales , giros y cheques de viajero sin emitir?','{"S6P4B2":{"Id":"S6P4B2","text":"", "code":"crimes6p4b2"}}','2091',''),
                                                                                                                                          (2094,'2','OPTIONAL','iii','Dormant accounts of depositors?-Cuentas de depositos inactivas?','{"S6P4B3":{"Id":"S6P4B3","text":"", "code":"crimes6p4b3"}}','2091',''),
                                                                                                                                          (2095,'2','OPTIONAL','iv','Access Codes, cypers and test keys?-Códigos de acceso, cifras, claves y llaves maestras?','{"S6P4B4":{"Id":"S6P4B4", "text":"","code":"crimes6p4b4"}}','2091',''),
                                                                                                                                          (2096,'2','DES','','"Dual control" is understood as the work of one person in processing transactions being verified by a second person and both sharing the accountability.-Se entiende por "Doble Control" que el trabajo de una persona en el procesamiento de transacciones sea verificado por una segunda persona y ambos sean responsables por la tarea.','','2078',''),

                                                                                                                                          (2097,'2','OPTIONAL','5','Is there an internal audit department which has separate duties from the auditing services provided by an external accountant?-Existe un Departamento de Auditoria Interna que tiene deberes distintos a los servicios de auditoria proporcinados por un contable externo?, If so,-En caso afirmativo','{"S6P5":{"Id":"S6P5", "text":"","code":"crimes6p5"}}','',''),
                                                                                                                                          (2098,'2','OPTIONAL','a','Is there an "audit and control procedures"manual and programme which includes electronic Data Processing Audit?-Existe algún manual de "Procedimiento de Auditoria y Control" y programa que incluya procesimiento de datos electronicos?','{"S6P5A":{"Id":"S6P5A","text":"", "code":"crimes6p5a"}}','2097',''),
                                                                                                                                          (2099,'2','SUB','b','How many people are employed in the internal audit department?-Con cuánto personal cuenta dicho departamento?','{"S6P5B":{"Id":"S6P5B","text":"", "code":"crimes6p5b"}}','2097',''),
                                                                                                                                          (2100,'2','SUB','c','How often are full internal audits made?-Con que frecuencia se realizan Auditorias Internas completas?','{"S6P5C":{"Id":"S6P5C","text":"", "code":"crimes6p5c"}}','2097',''),
                                                                                                                                          (2101,'2','OPTIONAL','d','Are audits made regularly on a surprise basis?-Las auditorias se efectúan normalmente sin aviso previo?','{"S6P5D":{"Id":"S6P5D","text":"", "code":"crimes6p5d"}}','2097',''),
                                                                                                                                          (2102,'2','OPTIONAL','e','Are all departments and premises, including computer centres and facilities included in the audit?-Están incluidas en la Auditoria todas las oficinas y departamentosincluso los centros informáticos, asi como todas las instalaciones?','{"S6P5E":{"Id":"S6P5E","text":"", "code":"crimes6p5e"}}','2097',''),
                                                                                                                                          (2103,'2','OPTIONAL','f','Are the persons responsible for the auditing forbidden to originate entries?-Les esta prohibido al personal responsible de la Auditoria efectuar registros contables?','{"S6P5F":{"Id":"S6P5F","text":"", "code":"crimes6p5f"}}','2097',''),

                                                                                                                                          (2104,'2','OPTIONAL-NORMAL','6a-b','Are you audited annually by an outside firm of Chartered, Certified or Professional Auditors or Accountants?-Se lleva a cabo una auditoria anual por una empresa externa registrada, certificada o profesional de Auditores o Contables?. - If so please state name - En caso afirmativo, por favor indicar su nombre','{"S6P6A":{"Id":"S6P6A","text":"", "code":"crimes6p6a"}}','',''),
                                                                                                                                          (2105,'2','OPTIONAL-NORMAL','c-i-ii','Does the audit include all the proposers offices?-La auditoia comprende todas las oficinas del proponente?-If no, what extent does the audit take?-En caso negativo, que extension tiene la auditoria? ','{"S6P6C1":{"Id":"S6P6C1","text":"", "code":"crimes6p6c1"}}','2104',''),
                                                                                                                                          (2106,'2','OPTIONAL','d','Do the auditors visit all locations?-Los Auditores visitan todas las sucursales, agencias y delegaciones?','{"S6P6D":{"Id":"S6P6D","text":"", "code":"crimes6p6d"}}','2104',''),
                                                                                                                                          (2107,'2','OPTIONAL','e-i','Does the firm or Authority regularly review the system of internal control and furnish written reports?-La firma de Auditores o Autoridades revisan regularmente el sistema de controles internos y suministran informes escritos?','{"S6P6E1":{"Id":"S6P6E1","text":"", "code":"crimes6p6e1"}}','2104',''),
                                                                                                                                          (2108,'2','OPTIONAL','ii','If so, do these reports go directly to the Board of Directors?-En caso afirmativo, van esos informes directamente al Consejo de Administración?','{"S6P6E2":{"Id":"S6P6E2","text":"", "code":"crimes6p6e2"}}','2107',''),
                                                                                                                                          (2109,'2','OPTIONAL-NORMAL','iii','Has the last such audit resulted in any qualified opinions?-Se obtiene de la última auditoria  cualquier comentario o sugerencia?-If yes please describe.-En caso afirmativo describe las cualificaciones y sugerencias','{"S6P6E3":{"Id":"S6P6E3","text":"", "code":"crimes6p6e3"}}','2107','');


INSERT INTO QUESTION (IDQUESTION,IDQUESTIONNAIRE,TYPEQUESTION, DESCRIPTIONQUESTION ,QUESTIONTEXT ,QUESTIONJSON ,PARENTID ,DOCUMENTID) VALUES
                                                                                                                                          (2110,'2','DES','','SECTION G – INTERNAL CONTROLS AND PROCEDURES, AUDIT AND COMPLIANCE / CONTROLES Y PROCEDIMIENTOS INTERNOS, AUDITORIA Y SEGUIMIENTO','','',''),
                                                                                                                                          (2111,'2','SUB','','VAULTS AND STRONGROOMS-BOVEDAS Y CAMARAS ACORAZADAS','{"S7P1R1":{"Id":"S7P1R1", "text":"Head Office-Casa Matriz"},"S7P1R2":{"Id":"S7P1R2", "text":"Main Branches-Sucursales Principales"},"S7P1R3":{"Id":"S7P1R3", "text":"All Other Locations-Todos los demás locales"}}','2110',''),
                                                                                                                                          (2112,'2','DES','1-a','Are there vaults and strongrooms on the premises?-Se encuentran Bóvedas y Camaras Acorazadas ubicadas en locales del Proponente?','{"S7P1AR1":{"Id":"S7P1AR1", "text":"","code":"crimes7p1ar1"},"S7P1AR2":{"Id":"S7P1AR2", "text":"","code":"crimes7p1ar2"},"S7P1AR3":{"Id":"S7P1AR3", "text":"","code":"crimes7p1ar3"}}','2110',''),
                                                                                                                                          (2113,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P1AR1":{"Id":"S7P1AR1","text":"","code":"crimes7p1ar1"}}','2112',''),
                                                                                                                                          (2114,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P1AR2":{"Id":"S7P1AR2","text":"","code":"crimes7p1ar2"}}','2112',''),
                                                                                                                                          (2115,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P1AR3":{"Id":"S7P1AR3","text":"","code":"crimes7p1ar3"}}','2112',''),
                                                                                                                                          (2116,'2','NORMAL','1-b','If yes, are they equipped with, En caso afirmativo, están equipadas con:','','2112','crimes7p1b'),

                                                                                                                                          (2117,'2','DES','i','A dial combination lock? Cerradura con combinación (contraseña)','','2110',''),
                                                                                                                                          (2118,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P1B1R1":{"Id":"S7P1B1R1","text":"","code":"crimes7p1b1r1"}}','2117',''),
                                                                                                                                          (2119,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P1B1R2":{"Id":"S7P1B1R2","text":"","code":"crimes7p1b1r2"}}','2117',''),
                                                                                                                                          (2120,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P1B1R3":{"Id":"S7P1B1R3","text":"","code":"crimes7p1b1r3"}}','2117',''),

                                                                                                                                          (2121,'2','DES','ii','Time lock-Cerradura con mechanismo de tiempo','','2110',''),
                                                                                                                                          (2122,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P1B2R1":{"Id":"S7P1B2R1","text":"","code":"crimes7p1b2r1"}}','2121',''),
                                                                                                                                          (2123,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P1B2R2":{"Id":"S7P1B2R2","text":"","code":"crimes7p1b2r2"}}','2121',''),
                                                                                                                                          (2124,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P1B2R3":{"Id":"S7P1B2R3","text":"","code":"crimes7p1b2r3"}}','2121',''),

                                                                                                                                          (2125,'2','DES','iii','a lockable day gate?-Puertas que puedan cerrarse con clave durante el dia?','','2110',''),
                                                                                                                                          (2126,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P1B3R1":{"Id":"S7P1B3R1","text":"","code":"crimes7p1b3r1"}}','2125',''),
                                                                                                                                          (2127,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P1B3R2":{"Id":"S7P1B3R2","text":"","code":"crimes7p1b3r2"}}','2125',''),
                                                                                                                                          (2128,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P1B3R3":{"Id":"S7P1B3R3","text":"","code":"crimes7p1b3r3"}}','2125',''),

                                                                                                                                          (2129,'2','DES','c-i',' Are the walls, floors and ceilings of reinforced concrete and lined with steel? Las paredes, suelos, techos son de hormigon armado y están forrades de acero?','','2110',''),
                                                                                                                                          (2130,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P1C1R1":{"Id":"S7P1C1R1", "text":"","code":"crimes7p1c1r1"}}','2129',''),
                                                                                                                                          (2131,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P1C1R2":{"Id":"S7P1C1R2","text":"","code":"crimes7p1c1r2"}}','2129',''),
                                                                                                                                          (2132,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P1C1R3":{"Id":"S7P1C1R3","text":"","code":"crimes7p1c1r3"}}','2129',''),

                                                                                                                                          (2133,'2','DES','ii','Are doors of arc, torch and drill resistive materials?-Las puertas son resistentes al corte por arco voltaico, al soplete y al taladro?','','2110',''),
                                                                                                                                          (2134,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P1C2R1":{"Id":"S7P1C2R1","text":"","code":"crimes7p1c2r1"}}','2133',''),
                                                                                                                                          (2135,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P1C2R2":{"Id":"S7P1C2R2","text":"","code":"crimes7p1c2r2"}}','2133',''),
                                                                                                                                          (2136,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P1C2R3":{"Id":"S7P1C2R3","text":"","code":"crimes7p1c2r3"}}','2133',''),

                                                                                                                                          (2137,'2','DES','iii','Do they have an anti explosive device in the doors?-Cuentan con un dispositivo anti-explosivo en las puertas?','','2110',''),
                                                                                                                                          (2138,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P1C3R1":{"Id":"S7P1C3R1", "text":"","code":"crimes7p1c3r1"}}','2137',''),
                                                                                                                                          (2139,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P1C3R2":{"Id":"S7P1C3R2", "text":"","code":"crimes7p1c3r2"}}','2137',''),
                                                                                                                                          (2140,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P1C3R3":{"Id":"S7P1C3R3", "text":"","code":"crimes7p1c3r3"}}','2137',''),

                                                                                                                                          (2141,'2','MULTIPLE','','If any of the above are answered "NO" please describe alternative method of or type of protection. Si la respuesta a alguna de las preguntas anteriores es "NO" describir el método alternativo o el tipo de protección.','{"S7P1DR1":{"Id":"S7P1DR1","text":"Head Office-Casa Matriz","code":"crimes7p1dr1"},"S7P1DR2":{"Id":"S7P1DR2","text":"Main Branches-Sucursales Principales","code":"crimes7p1dr2"},"S7P1DR3":{"Id":"S7P1DR3","text":"All Other Locations-Todos los demás locales","code":"crimes7p1dr3"}}','2110',''),

                                                                                                                                          (2142,'2','DES','2','SAFES / CAJAS FUERTES','','2110',''),

                                                                                                                                          (2143,'2','DES','a','Are there safes on the premises?-Se encuentran cajas fuertes en la oficinas?','','2142',''),
                                                                                                                                          (2144,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P2AR1":{"Id":"S7P2AR1", "text":"","code":"crimes7p2ar1"}}','2143',''),
                                                                                                                                          (2145,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P2AR2":{"Id":"S7P2AR2", "text":"","code":"crimes7p2ar2"}}','2143',''),
                                                                                                                                          (2146,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P2AR3":{"Id":"S7P2AR3", "text":"","code":"crimes7p2ar3"}}','2143',''),

                                                                                                                                          (2147,'2','DES','b','Are they equipped with combination locks with a relocking device that will effectively lock the door if the combination is punched?-Están equipadas con cerraduras de combinación con mecanismo de bloqueo que cierre efectivamente la puerta si la combinación fuese taladrada?','','2142',''),
                                                                                                                                          (2148,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P2BR1":{"Id":"S7P2BR1", "text":"","code":"crimes7p2br1"}}','2147',''),
                                                                                                                                          (2149,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P2BR2":{"Id":"S7P2BR2", "text":"","code":"crimes7p2br2"}}','2147',''),
                                                                                                                                          (2150,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P2BR3":{"Id":"S7P2BR3","text":"","code":"crimes7p2br3"}}','2147',''),

                                                                                                                                          (2151,'2','DES','c','Are doors of arc, torch and drill resistive material?-Las puertas son de materiales resistentes al corte de arco voltaico, soplete y taladro?','','2142',''),
                                                                                                                                          (2152,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P2CR1":{"Id":"S7P2CR1", "text":"","code":"crimes7p2cr1"}}','2151',''),
                                                                                                                                          (2153,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P2CR2":{"Id":"S7P2CR2", "text":"","code":"crimes7p2cr2"}}','2151',''),
                                                                                                                                          (2154,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P2CR3":{"Id":"S7P2CR3", "text":"","code":"crimes7p2cr3"}}','2151',''),

                                                                                                                                          (2155,'2','DES','d','Do safes have an anti-explosive device in the door? - Las puertas cuentan con dispositivos anti-explosivos?','','2142',''),
                                                                                                                                          (2156,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P2DR1":{"Id":"S7P2DR1", "text":"","code":"crimes7p2dr1"}}','2155',''),
                                                                                                                                          (2157,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P2DR2":{"Id":"S7P2DR2", "text":"","code":"crimes7p2dr2"}}','2155',''),
                                                                                                                                          (2158,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P2DR3":{"Id":"S7P2DR3", "text":"","code":"crimes7p2dr3"}}','2155',''),

                                                                                                                                          (2159,'2','DES','e','Are safes anchored to the floor or alternatively do they weigh not less than 680 kgs. (1500 lbs) empty?-Están las cajas de seguridad fijadas al suelo, o alternativamente pesan vacias no menos de 680 Kgs (1500Ibs)?','','2142',''),
                                                                                                                                          (2160,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P2ER1":{"Id":"S7P2ER1", "text":"","code":"crimes7p2er1"}}','2159',''),
                                                                                                                                          (2161,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P2ER2":{"Id":"S7P2ER2", "text":"","code":"crimes7p2er2"}}','2159',''),
                                                                                                                                          (2162,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P2ER3":{"Id":"S7P2ER3", "text":"","code":"crimes7p2er3"}}','2159',''),

                                                                                                                                          (2163,'2','MULTIPLE','','If any of the above are answered "NO" please describe alternative method of or type of protection-Si la respuesta a alguna de las preguntas fuese "NO", describir el método alternativo o el tipo de protección.','{"S7P2FR1":{"Id":"S7P2FR1", "text":"Head Office-Casa Matriz","code":"crimes7p2fr1"},"S7P2FR2":{"Id":"S7P2FR2", "text":"Main Branches-Sucursales Principales","code":"crimes7p2fr2"},"S7P2FR3":{"Id":"S7P2FR3", "text":"All Other Locations-Todos los demás locales","code":"crimes7p2fr3"}}','2142',''),

                                                                                                                                          (2164,'2','DES','3','DOORS AND WINDOWS / PUERTAS Y VENTANAS','','2110',''),

                                                                                                                                          (2165,'2','DES','a','Are all doors fitted with substantial locks?-Las puertas están provistas de cerraduras solidas?','','2164',''),
                                                                                                                                          (2166,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P3AR1":{"Id":"S7P3AR1", "text":"","code":"crimes7p3ar1"}}','2165',''),
                                                                                                                                          (2167,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P3AR2":{"Id":"S7P3AR2", "text":"","code":"crimes7p3ar2"}}','2165',''),
                                                                                                                                          (2168,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P3AR3":{"Id":"S7P3AR3", "text":"","code":"crimes7p3ar3"}}','2165',''),

                                                                                                                                          (2169,'2','DES','b','Are all windows fitted with substantial locks or barred?-Las ventanas están provistas de cerraduras solidas o  rejas / barrotes?','','2164',''),
                                                                                                                                          (2170,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P3BR1":{"Id":"S7P3BR1", "text":"","code":"crimes7p3br1"}}','2169',''),
                                                                                                                                          (2171,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P3BR2":{"Id":"S7P3BR2", "text":"","code":"crimes7p3br2"}}','2169',''),
                                                                                                                                          (2172,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P3BR3":{"Id":"S7P3BR3", "text":"","code":"crimes7p3br3"}}','2169',''),

                                                                                                                                          (2173,'2','DES','4','ALARMS / ALARMAS','','2110',''),

                                                                                                                                          (2175,'2','DES','a','Are there alarm systems against Burglary?-Hay alarmas contra robo?','','2173',''),
                                                                                                                                          (2176,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P4AR1":{"Id":"S7P4AR1","text":"","code":"crimes7p4ar1"}}','2175',''),
                                                                                                                                          (2177,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P4AR2":{"Id":"S7P4AR2","text":"","code":"crimes7p4ar2"}}','2175',''),
                                                                                                                                          (2178,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P4AR3":{"Id":"S7P4AR3","text":"","code":"crimes7p4ar2"}}','2175',''),

                                                                                                                                          (2179,'2','SUB','b','If so to whom are they connected to:-Están conectados con:','{"S7P4B":{"Id":"S7P4B","text":"crimes7p4b"}}','2173',''),

                                                                                                                                          (2180,'2','DES','i','Police Station?-La comisaría de Policía?','','2173',''),
                                                                                                                                          (2181,'2','SUB','','Head Office-Casa Matriz','{"S7P4B1R1":{"Id":"S7P4B1R1","text":"","code":"crimes7p4b1r1"}}','2180',''),
                                                                                                                                          (2182,'2','SUB','','Main Branches-Sucursales Principales','{"S7P4B1R2":{"Id":"S7P4B1R2","text":"","code":"crimes7p4b1r2"}}','2180',''),
                                                                                                                                          (2183,'2','SUB','','All Other Locations-Todos los demás locales','{"S7P4B1R3":{"Id":"S7P4B1R3","text":"","code":"crimes7p4b1r2"}}','2180',''),

                                                                                                                                          (2184,'2','MULTIPLE','ii','Elsewhere (describe)?-Algun otro lugar (detallarlo)?','{"S7P4B2R1":{"Id":"S7P4B2R1","text":"Head Office-Casa Matriz","code":"crimes7p4b2r1"},"S7P4B2R2":{"Id":"S7P4B2R2","text":"Main Branches-Sucursales Principales","code":"crimes7p4b2r2"},"S7P4B2R3":{"Id":"S7P4B2R3","text":"All Other Locations-Todos los demás locales","code":"crimes7p4b2r3"}}','2179',''),


                                                                                                                                          (2185,'2','DES','5','TELLER POSITIONS VENTANILLAS DE CAJEROS','{"S7P5R1":{"Id":"S7P5R1","text":"Head Office-Casa Matriz"},"S7P5R2":{"Id":"S7P5R2","text":"Main Branches-Sucursales Principales"},"S7P5R3":{"Id":"S7P5R3","text":"All Other Locations-Todos los demás locales"}}','',''),

                                                                                                                                          (2186,'2','DES','a','Are there alarm systems against robbery?-Hay dispositivios de alarma contra asalto?','','2185',''),
                                                                                                                                          (2187,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P5AR1":{"Id":"S7P5AR1","text":"","code":"crimes7p5ar1"}}','2186',''),
                                                                                                                                          (2188,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P5AR2":{"Id":"S7P5AR2","text":"","code":"crimes7p5ar2"}}','2186',''),
                                                                                                                                          (2189,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P5AR3":{"Id":"S7P5AR3","text":"","code":"crimes7p5ar3"}}','2186',''),

                                                                                                                                          (2190,'2','DES','b','Does each teller position have a robbery alarm button or pedal out of view of the public?-Tiene cada cajero un boton o pedal de alarma fuera de la vista del público?','','2185',''),
                                                                                                                                          (2191,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P5BR1":{"Id":"S7P5BR1","text":"","code":"crimes7p5br1"}}','2190',''),
                                                                                                                                          (2192,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P5BR2":{"Id":"S7P5BR2","text":"","code":"crimes7p5br2"}}','2190',''),
                                                                                                                                          (2193,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P5BR3":{"Id":"S7P5BR3","text":"","code":"crimes7p5br3"}}','2190',''),

                                                                                                                                          (2194,'2','DES','c','Are tellers positions protected by anti-bandit glass?-Están protegidas las ventanillas con vidrios blindados / anti-robo?','','2185',''),
(2195,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P5CR1":{"Id":"S7P5CR1","text":"","code":"crimes7p5cr1"}}','2194',''),
(2196,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P5CR2":{"Id":"S7P5CR2","text":"","code":"crimes7p5cr2"}}','2194',''),
(2197,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P5CR3":{"Id":"S7P5CR3","text":"","code":"crimes7p5cr3"}}','2194',''),

(2198,'2','DES','d','Are tellers positions separated from the rest of the Banking Hall by a suitable partition with doors kept locked during Banking Hours?-Están las ventanillas separadas del resto de la oficina por una partición adecuada con sus puertas cerradas durante las horas de atención al publico?','','2185',''),
                                                                                                                                          (2199,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P5DR1":{"Id":"S7P5DR1","text":"","code":"crimes7p5dr1"}}','2198',''),
                                                                                                                                          (2200,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P5DR2":{"Id":"S7P5DR2","text":"","code":"crimes7p5dr2"}}','2198',''),
                                                                                                                                          (2201,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P5DR3":{"Id":"S7P5DR3","text":"","code":"crimes7p5dr3"}}','2198',''),

                                                                                                                                          (2202,'2','DES','e','Is cash in excess of the amounts referred to in Section C 2 of this proposal removed immediately to a locked safe, vault or other protected place?-Se transfiere el efectivo que excede los importes mencionados en la Pregunta 10 inmediatamente a una caja fuerte o camara acorazada u otro lugar protegido?','','2185',''),
                                                                                                                                          (2203,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P5ER1":{"Id":"S7P5ER1","text":"","code":"crimes7p5er1"}}','2202',''),
                                                                                                                                          (2204,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P5ER2":{"Id":"S7P5ER2","text":"","code":"crimes7p5er2"}}','2202',''),
                                                                                                                                          (2205,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P5ER3":{"Id":"S7P5ER3","text":"","code":"crimes7p5er3"}}','2202',''),

                                                                                                                                          (2206,'2','DES','f','Are all cashiers cash holdings taken to safe/vault when teller position is closed?-Se guardan todos los saldos en manos de los cajeros en una caja fuerte/camara acorazada despues del cierre de operaciones?','','2185',''),
                                                                                                                                          (2207,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P5FR1":{"Id":"S7P5FR1","text":"","code":"crimes7p5fr1"}}','2206',''),
                                                                                                                                          (2208,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P5FR2":{"Id":"S7P5FR2","text":"","code":"crimes7p5fr2"}}','2206',''),
                                                                                                                                          (2209,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P5FR3":{"Id":"S7P5FR3","text":"","code":"crimes7p5fr3"}}','2206',''),

                                                                                                                                          (2210,'2','DES','g','Are cashiers provided with "Bait"* or "Decoy"money?-Los cajeros están provistos de dinero marcado o "carnada."*','','2185',''),
                                                                                                                                          (2211,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P5GR1":{"Id":"S7P5GR1","text":"","code":"crimes7p5gr1"}}','2210',''),
                                                                                                                                          (2212,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P5GR2":{"Id":"S7P5GR2","text":"","code":"crimes7p5gr2"}}','2210',''),
                                                                                                                                          (2213,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P5GR3":{"Id":"S7P5GR3","text":"","code":"crimes7p5gr3"}}','2210',''),

                                                                                                                                          (2214,'2','DES','*Note: Bait money consists of currency notes the Denomination, serial numbers and serial years Of which have been recorded and verified by a second Employee and left in a safe place.  Such "bait" money should be given to cashiers to be handed out only in the event of the robbery.. -*Nota:	Dinero "carnada" consiste en dinero, el cual ha tenido su denominación, numero de serie y año de la serie anotado y verificado por un segundo empleado y dejado en un lugar seguro.  Tal dinero "carnad" deberá darse a los cajeros para que sea entregado solamente en caso de robo','5g. Are cashiers provided with "Bait"* or "Decoy"money?-Los cajeros están provistos de dinero marcado o "carnada."*','','2185',''),

(2215,'2','DES','6','GUARDS / VIGILANTES','','',''),

(2216,'2','DES','1-a','Do Police patrol and inspect premises ?-La policia patrulla e inspecciona los predios?','','2215',''),
(2217,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6AR1":{"Id":"S7P6AR1","text":"","code":"crimes7p6ar1"}}','2216',''),
(2218,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6AR2":{"Id":"S7P6AR2","text":"","code":"crimes7p6ar2"}}','2216',''),
(2219,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6AR3":{"Id":"S7P6AR3","text":"","code":"crimes7p6ar3"}}','2216',''),


(2220,'2','SUB','b','Do you have armed guards:-Tiene usted vigilantes armados?','{"S7P6B":{"Id":"S7P6B","text":"","code":"crimes7p6b"}}','2215',''),

(2221,'2','DES','i','by day? / Durante el dia?','','2220',''),
(2222,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6B1R1":{"Id":"S7P6B1R1","text":"","code":"crimes7p6b1r1"}}','2221',''),
(2223,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6B1R2":{"Id":"S7P6B1R2","text":"","code":"crimes7p6b1r2"}}','2221',''),
(2224,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6B1R3":{"Id":"S7P6B1R3","text":"","code":"crimes7p6b1r3"}}','2221',''),

(2225,'2','DES','ii','by night? / Durante la noche?','','2220',''),
(2226,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6B2R1":{"Id":"S7P6B2R1","text":"","code":"crimes7p6b2r1"}}','2225',''),
(2227,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6B2R2":{"Id":"S7P6B2R2","text":"","code":"crimes7p6b2r2"}}','2225',''),
(2228,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6B2R3":{"Id":"S7P6B2R3","text":"","code":"crimes7p6b2r3"}}','2225',''),

(2229,'2','SUB','c','Are they provided by-Son proporcionados por','{"S7P6CR1":{"Id":"S7P6CR1","text":"","code":"crimes7p6cr1"}}','2215',''),

(2230,'2','DES','i','Police ? - La Policia?','','2229',''),
(2231,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6C1R1":{"Id":"S7P6C1R1","text":"","code":"crimes7p6c1r1"}}','2230',''),
(2232,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6C2R2":{"Id":"S7P6C1R2","text":"","code":"crimes7p6c1r2"}}','2230',''),
(2233,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6C1R3":{"Id":"S7P6C1R3","text":"","code":"crimes7p6c1r3"}}','2230',''),

(2234,'2','DES','ii','Agency ? - Una agencia?','','2229',''),
(2235,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6C2R1":{"Id":"S7P6C2R1","text":"","code":"crimes7p6c2r1"}}','2234',''),
(2236,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6C2R2":{"Id":"S7P6C2R2","text":"","code":"crimes7p6c2r2"}}','2234',''),
(2237,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6C2R3":{"Id":"S7P6C2R3","text":"","code":"crimes7p6c2r3"}}','2234',''),

(2238,'2','DES','iii','The Bank itself ?-El Banco mismo?','','2229',''),
(2239,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6C3R1":{"Id":"S7P6C3R1","text":"","code":"crimes7p6c3r1"}}','2238',''),
(2240,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6C3R2":{"Id":"S7P6C3R2","text":"","code":"crimes7p6c3r2"}}','2238',''),
(2241,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6C3R3":{"Id":"S7P6C3R3","text":"","code":"crimes7p6c3r3"}}','2238',''),

(2242,'2','DES','d','Are they protected by bullet proof cages?-Están protegidos por casetas a prueba de bala?','','2215',''),
(2243,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6DR1":{"Id":"S7P6DR1","text":"","code":"crimes7p6dr1"}}','2242',''),
(2244,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6DR2":{"Id":"S7P6DR2","text":"","code":"crimes7p6dr2"}}','2242',''),
(2245,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6DR3":{"Id":"S7P6DR3","text":"","code":"crimes7p6dr3"}}','2242',''),

(2246,'2','DES','e','Please clarify if applicable at all locations-Clarificar si se aplica en todos .los locales','','2215',''),
(2247,'2','OPTIONAL','','Head Office-Casa Matriz','{"S7P6ER1":{"Id":"S7P6ER1","text":"","code":"crimes7p6er1"}}','2246',''),
(2248,'2','OPTIONAL','','Main Branches-Sucursales Principales','{"S7P6ER2":{"Id":"S7P6ER2","text":"","code":"crimes7p6er2"}}','2246',''),
(2249,'2','OPTIONAL','','All Other Locations-Todos los demás locales','{"S7P6ER3":{"Id":"S7P6ER3","text":"","code":"crimes7p6er3"}}','2246',''),

(2250,'2','DES','7','SAFE DEPOSIT BOXES / CAJAS DE SEGURIDAD','','',''),

(2251,'2','MULTIPLE','a-i','How many safe deposit boxes are there ?-Cuántas cajas de seguridad tienen?','{"S7P7A1R1":{"Id":"S7P7A1R1","text":"","code":"crimes7p7a1r1"},"S7P7A1R2":{"Id":"S7P7A1R2","text":"","code":"crimes7p7a1r2"},"S7P7A1R3":{"Id":"S7P7A1R3","text":"","code":"crimes7p7a1r3"}}','152',''),
(2252,'2','MULTIPLE','ii','How many of these are rented ?-Cuántas están alquiladas?','{"S7P7A2R1":{"Id":"S7P7A2R1","text":"","code":"crimes7p7a2r1"},"S7P7A2R2":{"Id":"S7P7A2R2","text":"","code":"crimes7p7a2r2"},"S7P7A2R3":{"Id":"S7P7A2R3","text":"","code":"crimes7p7a2r3"}}','2251',''),
(2253,'2','MULTIPLE','iii','How many locations provide safe deposit Facilities?-Cuántas oficinas/sucursales proveen Cajas de Seguridad?','{"S7P7A3R1":{"Id":"S7P7A3R1","text":"","code":"crimes7p7a3r1"},"S7P7A3R2":{"Id":"S7P7A3R2","text":"","code":"crimes7p7a3r2"},"S7P7A3R3":{"Id":"S7P7A3R3","text":"","code":"crimes7p7a3r3"}}','2251',''),

(2254,'2','DES','b','Are all safe deposit boxes in a separate Safe Deposit Vault ?-Están todas las Cajas de Seguridad ubicadas en una bóveda de seguridad separada?, If not, describe where they are kept.- Si no es asi, describa donde se encuentran?','','',''),
(2255,'2','OPTIONAL-NORMAL','','Head Office-Casa Matriz','{"S7P7B1R1":{"Id":"S7P7B1R1","text":"","code":"crimes7p7b1r1"}}','2254',''),
(2256,'2','OPTIONAL-NORMAL','','Main Branches-Sucursales Principales','{"S7P7B1R2":{"Id":"S7P7B1R2","text":"","code":"crimes7p7b1r2"}}','2254',''),
(2257,'2','OPTIONAL-NORMAL','','All Other Locations-Todos los demás locales','{"S7P7B1R3":{"Id":"S7P7B1R3","text":"","code":"crimes7p7b1r3"}}','2254',''),

(2258,'2','DES','ii','Are customers never left unattended in the main safe deposit box area?-Nunca se deja clientes desatendidos en el área principal de las cajas de seguridad?, If not, please detail what controls are in place.-Si no es asi, Por favor detallar que controles tienen','','2254',''),
(2259,'2','OPTIONAL-NORMAL','','Head Office-Casa Matriz','{"S7P7B2R1":{"Id":"S7P7B2R1","text":"","code":"crimes7p7b2r1"}}','2258',''),
(2260,'2','OPTIONAL-NORMAL','','Main Branches-Sucursales Principales','{"S7P7B2R2":{"Id":"S7P7B2R2","text":"","code":"crimes7p7b2r2"}}','2258',''),
(2261,'2','OPTIONAL-NORMAL','','All Other Locations-Todos los demás locales','{"S7P7B2R3":{"Id":"S7P7B2R3","text":"","code":"crimes7p7b2r3"}}','2258',''),

(2262,'2','DES','7','SAFE DEPOSIT BOXES / CAJAS DE SEGURIDAD','','',''),

(2263,'2','DES','','Are all safe deposit boxes maintained under dual control?*-Se mantiene todas las cajas de segurided bajo doble control?','','2262',''),
(2264,'2','OPTIONAL','','Head Office Casa Matriz','{"S7P7B222R1":{"Id":"S7P7B222R1","text":"","code":"crimes7p7cr1"}}','2263',''),
(2265,'2','OPTIONAL','','Main Branches Sucursales Principales','{"S7P7B222R2":{"Id":"S7P7B222R2","text":"","code":"crimes7p7cr2"}}','2263',''),
(2266,'2','OPTIONAL','','All Other Locations Todos los demás locales','{"S7P7B222R3":{"Id":"S7P7B222R3","text":"","code":"crimes7p7cr3"}}','2263',''),

(2267,'2','DES','','*"Dual control" means that the Safe Deposit Box can only be opened by two keys, one key retained by the bank and the other key kept by the customer.-Se entiende por "Doble Control" que solo se puede abrir la Caja De Seguridad con dos llaves, una retenida por el banco y la otra llave mantenido por el cliente.','','2262',''),

(2268,'2','DES','','8. TRANSIT / TRANSPORTE','','',''),

(2269,'2','DES','a-i','Is transfer of money and negotiable securities carried out by a third party Security / Armoured  Motor Vehicle company ?-Es el dinero y valores negociables traslado por una Compañía de translados de fondos / Compania de Seguridad - de terceros?','','2268',''),
(2270,'2','OPTIONAL','','Head Office Casa Matriz','{"S7P8A1R1":{"Id":"S7P8A1R1","text":"","code":"crimes7p8a1r1"}}','2269',''),
(2271,'2','OPTIONAL','','Main Branches Sucursales Principales','{"S7P8A1R2":{"Id":"S7P8A1R2","text":"","code":"crimes7p8a1r2"}}','2269',''),
(2272,'2','OPTIONAL','','All Other Locations Todos los demás locales','{"S7P8A1R3":{"Id":"S7P8A1R3","text":"","code":"crimes7p8a1r3"}}','2269',''),

(2273,'2','DES','',' If so, does the Security / Armoured Motor Vehicle company have full insurance and accept full responsibility for all values transported-En caso afirmativo, tiene la compañía de Seguridad,/compañía de transporte de fondos  una póliza de seguros y acceptan la responsabilidad para todos los valores transportados','','2269',''),
(2274,'2','OPTIONAL','','Head Office Casa Matriz','{"S7P8A11R1":{"Id":"S7P8A11R1","text":"","code":"crimes7p8a11r1"}}','2273',''),
(2275,'2','OPTIONAL','','Main Branches Sucursales Principales','{"S7P8A11R2":{"Id":"S7P8A11R2","text":"","code":"crimes7p8a11r2"}}','2273',''),
(2276,'2','OPTIONAL','','All Other Locations Todos los demás locales','{"S7P8A11R3":{"Id":"S7P8A11R3","text":"","code":"crimes7p8a11r3"}}','2273',''),


(2277,'2','SUB','ii','If not please provide full details of transit arrangements on a separate page-Si no es así Por favor proporcionar detalles completas con respeto a sus traslados usando otra hoja: ','{"S7P8A2R1":{"Id":"S7P8A2R1","text":"","code":"crimes7p8a2r1"}}','2268',''),

(2278,'2','DES','b','is transit of Money and negotiable securities carried out by messengers?-Se transporte efectivo y valores negociables por mensajero?, If yes, how many messengers do you employ?-En caso afirmativo, cuantos mensajeros contratan?','','163',''),
(2279,'2','OPTIONAL-NORMAL','','Head Office Casa Matriz','{"S7P8BR1":{"Id":"S7P8BR1","text":"","code":"crimes7p8br1"}}','2278',''),
(2280,'2','OPTIONAL-NORMAL','','Main Branches Sucursales Principales','{"S7P8BR2":{"Id":"S7P8BR2","text":"","code":"crimes7p8br2"}}','2278',''),
(2281,'2','OPTIONAL-NORMAL','','All Other Locations Todos los demás locales','{"S7P8BR3":{"Id":"S7P8BR3","text":"","code":"crimes7p8br3"}}','2278',''),

(2282,'2','DES','ii','If yes, are all messengers accompanied by police or armed guards?-En caso afirmativo son todos los mensajeros acompañados por Policía o guardías armados?','','2268',''),
(2283,'2','OPTIONAL','','Head Office Casa Matriz','{"S7P8B2R1":{"Id":"S7P8B2R1","text":"","code":"crimes7p8b2r1"}}','2282',''),
(2284,'2','OPTIONAL','','Main Branches Sucursales Principales','{"S7P8B2R2":{"Id":"S7P8B2R2","text":"","code":"crimes7p8b2r2"}}','2282',''),
(2285,'2','OPTIONAL','','All Other Locations Todos los demás locales','{"S7P8B2R3":{"Id":"S7P8B2R3","text":"","code":"crimes7p8b2r3"}}','2282',''),

(2286,'2','DES','c','Are trips scheduled at irregular intervals and over varying routes:-Son los translados  programados a intervalos irregulares y variando las  rutas?','{"S7P8CR1":{"Id":"S7P8CR1","text":"","code":"crimes7p8cr1"},"S7P8CR2":{"Id":"S7P8CR2","text":"","code":"crimes7p8cr2"},"S7P8CR3":{"Id":"S7P8CR3","text":"","code":"crimes7p8cr3"}}','2268',''),
(2287,'2','OPTIONAL','','Head Office Casa Matriz','{"S7P8CR1":{"Id":"S7P8CR1","text":"","code":"crimes7p8cr1"}}','2286',''),
(2288,'2','OPTIONAL','','Main Branches Sucursales Principales','{"S7P8CR2":{"Id":"S7P8CR2","text":"","code":"crimes7p8cr2"}}','2286',''),
(2289,'2','OPTIONAL','','All Other Locations Todos los demás locales','{"S7P8CR3":{"Id":"S7P8CR3","text":"","code":"crimes7p8cr3"}}','2286',''),


(2290,'2','DES','','SECTION H – COMPUTER SYSTEMS / SISTEMAS INFORMATICOS','','',''),

(2291,'2','OPTIONAL','1','Do you operate or subscribe  to any automated teller machine network or electronic point of sale system?-Opera o está suscrito a alguna red de cajeros automáticos o sistema electrónico de puntos de venta?','{"S8P1":{"Id":"S8P1","text":"","code":"crimes8p1"}}','2290',''),

(2292,'2','DES','2-a','Do you make or receive funds transfer instruction via any of the following methods?-Realiza o recibe instrucciones para transferencias de fondos por alguna de las siguientes vías?','','2290',''),
(2293,'2','OPTIONAL','i','BACS','{"S8P2A1":{"Id":"S8P2A1","text":"","code":"crimes8p2a1"}}','2292',''),
(2294,'2','OPTIONAL','ii','SWIFT','{"S8P2A2":{"Id":"S8P2A2","text":"","code":"crimes8p2a2"}}','2292',''),
(2295,'2','OPTIONAL','iii','CHAPS','{"S8P2A3":{"Id":"S8P2A3","text":"","code":"crimes8p2a3"}}','2292',''),
(2296,'2','OPTIONAL','iv','Bankwire','{"S8P2A4":{"Id":"S8P2A4","text":"","code":"crimes8p2a4"}}','2292',''),
(2297,'2','OPTION-NORMAL','v','Other, please specify / otro, por favor especificar','{"S8P2A5":{"Id":"S8P2A5","text":"","code":"crimes8p2a5"}}','2292',''),

(2298,'2','DES','3','If you use wire transfer system for the movement of funds, please state:-Si usan transferencias electronicas para fondos, por favor indicar:','','2290',''),
(2299,'2','MULTIPLE','a','Average number of funds transfers executed per month:-Promedio de transferencias de fondos cada mes:','{"S8P3AR1":{"Id":"S8P3AR1","text":"For the banks account-Para las cuentas propias del banco","code":"crimes8p3ar1"},"S8P3AR2":{"Id":"S8P3AR2","text":"For the banks customers-Para clientes del banco","code":"crimes8p3ar2"}}','2298',''),
(2300,'2','MULTIPLE','b','Average Value any single transfer:-Valor promedio de una transferencia:','{"S8P3BR1":{"Id":"S8P3BR1","text":"For the banks account-Para las cuentas propias del banco","code":"crimes8p3br1"},"S8P3BR2":{"Id":"S8P3BR2","text":"For the banks customers-Para clientes del banco","code":"crimes8p3br2"}}','2298',''),
(2301,'2','MULTIPLE','c','Maximum value of any single transfer:-Valor maximo de una transferencia:','{"S8P3CR1":{"Id":"S8P3CR1","text":"For the banks account-Para las cuentas propias del banco","code":"crimes8p3cr1"},"S8P3CR2":{"Id":"S8P3CR2","text":"For the banks customers-Para clientes del banco","code":"crimes8p3cr2"}}','2298',''),

(2302,'2','OPTIONAL','','4. Are all fund transfer instructions subject to a verification and authentication process?-Están todas las instrucciones para transferencias de fondos sujetas a un proceso de verificación y autentificación?','{"S8P4":{"Id":"S8P4","text":"","code":"crimes8p4"}}','2290',''),

(2303,'2','OPTIONAL','','5. Do you secure fund transfer instructions (e.g. through the use of passwords, encryption, testing, call back or other authentication)?-Son verificadas todas las instrucciones para transferencias de fondos (por ejemplo mediante el uso de claves, texto disimulado, pruebas, "call-back" u otra autentificación)?','{"S8P5":{"Id":"S8P5","text":"","code":"crimes8p5"}}','2290',''),

(2304,'2','OPTIONAL-NORMAL','6','Do you permit the transfer of funds via electronic instruction?-Permite transferencias de fondos por vía de instrucción electrónica?, If "yes", in respect of corporate or business accounts only:-En caso afirmativo, en el caso de  cuentas corporitivas, o personas jurídicas:','{"S8P6":{"Id":"S8P6","text":"","code":"crimes8p6"}}','2290',''),
(2305,'2','OPTIONAL','a','Is there a written agreement with customers?-Existe un acuerdo escrito con los clientes?','{"S8P6A":{"Id":"S8P6A","text":"","code":"crimes8p6a"}}','2304',''),
(2306,'2','OPTIONAL','b','Does the written agreement contain transfer limits?-Contiene el acuerdo escrito límites de transferencias?','{"S8P6B":{"Id":"S8P6B","text":"","code":"crimes8p6b"}}','2304',''),
(2307,'2','OPTIONAL','c','Is verification, by someone other than the initiator of the transfer instruction, required prior to such transfer taking place?-Se requiere verificación por parte de una persona distinta al iniciante de la instrucción , previo a la ejecución de la transferencia?','{"S8P6C":{"Id":"S8P6c","text":"","code":"crimes8p6c"}}','2304',''),

(2308,'2','OPTIONAL','7','Are passwords used to give varying levels of access to your computer system and fund transfer system on the need and authorisation of user basis?-Son utilizadas claves para los distintos  niveles de acceso a un sistema de informatica y sistema de traspaso de fondos, dependiendo en la necesidad y autorización del usario?','{"S8P7":{"Id":"S8P7","text":"","code":"crimes8p7"}}','2290',''),

(2309,'2','OPTIONAL','8','Are all key source documents maintained in a secure environment prior to being entered into the computer system in order to prevent unauthorised modification or inappropriate use of data?-Son mantenidos todos los documentos claves en una ubicación segura previo a ser incluidos en la sistema de computación, de forma de prevenir la modificación  sin autorización o uso inapropiado de datos?','{"S8P8":{"Id":"S8P8","text":"","code":"crimes8p8"}}','2290',''),

(2310,'2','OPTIONAL','9','Are remote terminals kept in a physically secure location accessible by authorised personnel only?-Son los terminales remotos mantenidos en un ambiente físicamente seguro, con acceso restringido a personal autorizado únicamente?','{"S8P9":{"Id":"S8P9","text":"","code":"crimes8p9"}}','2290',''),

(2311,'2','OPTIONAL','10','Do you utilise any recognised software packages to control access to your computer system?-Utiliza paquetes de software reconocidos que controlan el acceso a su sistema informatico?','{"S8P10":{"Id":"S8P10","text":"","code":"crimes8p10"}}','2290',''),

(2312,'2','OPTIONAL','11','Are your data processing centres physically separated from other departments?-Estan sus centros de procesamiento de datos separados físicamente de los otros departamentos?','{"S8P11":{"Id":"S8P11","text":"","code":"crimes8p11"}}','2290',''),

(2313,'2','OPTIONAL','12','Do you have access control system for your data processing centres?-Tiene un sistema de control de acceso a su centro de procesamiento de datos?','{"S8P12":{"Id":"S8P12","text":"","code":"crimes8p12"}}','2290',''),

(2314,'2','OPTIONAL','13','Are data file generations stored and secured off-site in a restricted area?-Son las informaciones emanadas de archivos de datos guardadas y aseguradas en zonas restringidas?','{"S8P13":{"Id":"S8P13","text":"","code":"crimes8p13"}}','2290',''),

(2315,'2','OPTIONAL','14','Do you utilise independent contractors to prepare electronic computer programmes? If "yes"- Utiliza contratistas independientes para preparar programas informáticos?  En caso afirmativo:','{"S8P14":{"Id":"S8P14","text":"","code":"crimes8p14"}}','2290',''),
(2316,'2','OPTIONAL','a','Are specific parameters in place to restrict their access?-Existen parámetros específicos para restringir su acceso?','{"S8P14A":{"Id":"S8P14A","text":"","code":"crimes8p14a"}}','2315',''),
(2317,'2','OPTIONAL','b','Are their activities overseen when accessing your computer system?-Son supervisadas sus actividades cuando accedan a su sistema informatico?','{"S8P14B":{"Id":"S8P14B","text":"","code":"crimes8p14b"}}','2315',''),
(2318,'2','OPTIONAL','c','Are safeguards in place to prevent access to your other systems?-Existen medidas de seguridad para impedir el acceso a sus demás sistemas?','{"S8P14C":{"Id":"S8P14C","text":"","code":"crimes8p14c"}}','2315',''),

(2319,'2','DES','FUND/INVESTMENT/ASSET MANAGEMENT COMPANIES / FONDOS / COMPAÑIAS DE INVERSION Y MANEJO DE FONDOS','','','',''),
(2320,'2','DES','Only complete if the Proposer offers such services to third parties / Solo llenar en caso de que el Proponente ofrezca dichos servicios a Terceras Personas','','','2319',''),

(2321,'2','OPTIONAL','','1.Are transactions only entered into on the basis of appropriate authorisation in accordance with management criteria?-Son las transacciones únicamente ejecutadas con la apropiada autorización de acuerdo con los criterios de la dirección?','{"S9P1":{"Id":"S9P1","text":"","code":"crimes9p1"}}','2319',''),

(2322,'2','OPTIONAL','','2.Has management defined and communicated  formal trading policies and dealing limits?-Ha definido y comunicado la gerencia/directiva póliticas formales de transacciones así como limites transaccionales?','{"S9P2":{"Id":"S9P2","text":"","code":"crimes9p2"}}','2319',''),

(2323,'2','OPTIONAL','','3.Are trading transactions and positions reviewed for compliance with formal trading 	policies manual or similar internal document?-Son revisadas las transacciones y posiciones para evaluar su conformidad con manuales de póliticas transaccionales o algún documento interno similar?','{"S9P3":{"Id":"S9P3","text":"","code":"crimes9p3"}}','2319',''),

(2324,'2','OPTIONAL','','4.Are accounts of trades which exceed set limits identified or rectified or referred to senior management for immediate action?-Son las transacciones que exceden de límites establecidos identificados, rectificados o referidos a niveles superiores de gerencia para que acciones inmediatas sean tomadas?','{"S9P4":{"Id":"S9P4","text":"","code":"crimes9p4"}}','2319',''),

(2325,'2','OPTIONAL','','5.Do Counter parties receive authorised confirmation for all deals prior to settlement?-Recíben las contra-partes confirmación autorizada de toda negociación previas al pago de la mísma?','{"S9P5":{"Id":"S9P5","text":"","code":"crimes9p5"}}','2319',''),

(2326,'2','OPTIONAL','','6.Is the book of investments and securities periodically substantiated and evaluated against recorded values independently of the dealer and fund managers?-Es la cartera de inversiones periodicamente revisada y evaluada contra valores históricos , independientemente del negociador y gerente del fondo?','{"S9P6":{"Id":"S9P6","text":"","code":"crimes9p6"}}','2319',''),

(2327,'2','OPTIONAL','','7.Are responsibilities for investment decisions segregated from accounting activities and custodial responsibities?-Estan las responsabilidades de las decisiones de inversión separadas de las actividades contables así como de las responsabilidades de custodia?','{"S9P7":{"Id":"S9P7","text":"","code":"crimes9p7"}}','2319','');

INSERT INTO OPTIONS (idQUESTION,OPTIONTEXT,CREATEDAT) VALUES 
('2043','yes-no',''),
('2044','yes-no',''),
('2045','yes-no',''),
('2046','yes-no',''),
('2050','yes-no',''),
('2074','Date Of Discovery/Fecha de Descubrimiento - Nature O Loss/Naturaleza de la pérdida - Location/Oficina - Amount of Loss (BEFORE the application of any deductible) / Cantidad (ANTES de la aplicación de cualquier franquicia)',''),
('2075','##yes-no',''),
('2076','##yes-no',''),
('2077','##yes-no',''),
('2079','yes-no',''),
('2080','yes-no',''),
('2081','yes-no',''),
('2082','yes-no',''),
('2083','yes-no',''),
('2084','yes-no',''),
('2085','yes-no',''),
('2086','yes-no',''),
('2087','yes-no',''),
('2088','yes-no',''),
('2089','yes-no',''),
('2092','yes-no',''),
('2093','yes-no',''),
('2094','yes-no',''),
('2095','yes-no',''),
('2097','yes-no',''),
('2098','yes-no',''),
('2101','yes-no',''),
('2102','yes-no',''),
('2103','yes-no',''),
('2104','##yes-no',''),
('2105','yes-##no',''),
('2106','yes-no',''),
('2107','yes-no',''),
('2108','yes-no',''),
('2109','##yes-no',''),
('2113','yes-no',''),
('2114','yes-no',''),
('2115','yes-no',''),
('2118','yes-no',''),
('2119','yes-no',''),
('2120','yes-no',''),
('2122','yes-no',''),
('2123','yes-no',''),
('2124','yes-no',''),
('2126','yes-no',''),
('2127','yes-no',''),
('2128','yes-no',''),
('2130','yes-no',''),
('2131','yes-no',''),
('2132','yes-no',''),
('2134','yes-no',''),
('2135','yes-no',''),
('2136','yes-no',''),
('2138','yes-no',''),
('2139','yes-no',''),
('2140','yes-no',''),
('2144','yes-no',''),
('2145','yes-no',''),
('2146','yes-no',''),
('2148','yes-no',''),
('2149','yes-no',''),
('2150','yes-no',''),
('2152','yes-no',''),
('2153','yes-no',''),
('2154','yes-no',''),
('2156','yes-no',''),
('2157','yes-no',''),
('2158','yes-no',''),
('2160','yes-no',''),
('2161','yes-no',''),
('2162','yes-no',''),
('2166','yes-no',''),
('2167','yes-no',''),
('2168','yes-no',''),
('2170','yes-no',''),
('2171','yes-no',''),
('2172','yes-no',''),
('2176','yes-no',''),
('2177','yes-no',''),
('2178','yes-no',''),
('2181','yes-no',''),
('2182','yes-no',''),
('2183','yes-no',''),
('2187','yes-no',''),
('2188','yes-no',''),
('2189','yes-no',''),
('2191','yes-no',''),
('2192','yes-no',''),
('2193','yes-no',''),
('2195','yes-no',''),
('2196','yes-no',''),
('2197','yes-no',''),
('2199','yes-no',''),
('2200','yes-no',''),
('2201','yes-no',''),
('2203','yes-no',''),
('2204','yes-no',''),
('2205','yes-no',''),
('2207','yes-no',''),
('2208','yes-no',''),
('2209','yes-no',''),
('2211','yes-no',''),
('2212','yes-no',''),
('2213','yes-no',''),
('2217','yes-no',''),
('2218','yes-no',''),
('2219','yes-no',''),
('2222','yes-no',''),
('2223','yes-no',''),
('2224','yes-no',''),
('2226','yes-no',''),
('2227','yes-no',''),
('2228','yes-no',''),
('2231','yes-no',''),
('2232','yes-no',''),
('2233','yes-no',''),
('2235','yes-no',''),
('2236','yes-no',''),
('2237','yes-no',''),
('2239','yes-no',''),
('2240','yes-no',''),
('2241','yes-no',''),
('2243','yes-no',''),
('2244','yes-no',''),
('2245','yes-no',''),
('2247','yes-no',''),
('2248','yes-no',''),
('2249','yes-no',''),
('2251','yes-no',''),
('2252','yes-no',''),
('2253','yes-no',''),
('2255','yes-##no',''),
('2256','yes-##no',''),
('2257','yes-##no',''),
('2259','yes-##no',''),
('2260','yes-##no',''),
('2261','yes-##no',''),
('2264','yes-no',''),
('2265','yes-no',''),
('2266','yes-no',''),
('2270','yes-no',''),
('2271','yes-no',''),
('2272','yes-no',''),
('2274','yes-no',''),
('2275','yes-no',''),
('2276','yes-no',''),
('2279','##yes-no',''),
('2280','##yes-no',''),
('2281','##yes-no',''),
('2283','yes-no',''),
('2284','yes-no',''),
('2285','yes-no',''),
('2287','yes-no',''),
('2288','yes-no',''),
('2289','yes-no',''),
('2291','yes-no',''),
('2293','yes-no',''),
('2294','yes-no',''),
('2295','yes-no',''),
('2296','yes-no',''),
('2297','##X',''),
('2302','yes-no',''),
('2303','yes-no',''),
('2304','##yes-no',''),
('2305','yes-no',''),
('2306','yes-no',''),
('2307','yes-no',''),
('2308','yes-no',''),
('2309','yes-no',''),
('2310','yes-no',''),
('2311','yes-no',''),
('2312','yes-no',''),
('2313','yes-no',''),
('2314','yes-no',''),
('2315','yes-no',''),
('2316','yes-no',''),
('2317','yes-no',''),
('2318','yes-no',''),
('2321','yes-no',''),
('2322','yes-no',''),
('2323','yes-no',''),
('2324','yes-no',''),
('2325','yes-no',''),
('2326','yes-no',''),
('2327','yes-no','');