INSERT INTO QUESTIONNAIRE (IDQUESTIONNAIRE ,IDINSURANCE , NAMEQUESTIONNAIRE, DESCRIPTION, CREATEDAT, STATUS, SOURCEFILE, TOTALQUESTION) VALUES ('1','1','CUESTIONARIO COVID-19 ','CUESTIONARIO COVID-19 Template','','TRUE','CUESTIONARIOCOVID19.docx',29);



INSERT INTO QUESTION (IDQUESTION,IDQUESTIONNAIRE,TYPEQUESTION, DESCRIPTIONQUESTION ,QUESTIONTEXT ,QUESTIONJSON ,PARENTID ,DOCUMENTID) VALUES 
(1001,'1','NORMAL','1','¿Qué planes de contingencia han sido adoptados por la Compañía con respecto al coronavirus?; ¿O aún están en etapa de diseñar estos planes?; De ser así, ¿se ha contratado la asesoría de consultores externos especializados para este fin? / What contingency plans have been adopted by the Company with respect to the coronavirus, or are these plans still in the design stage?; If so, have specialized external consultants been hired for this purpose?','','','Covid1'),
(1002,'1','NORMAL','2','¿La Compañía ha identificado las fuentes de disrupciones causadas por la crisis del COVID-19 que han impactado o que son muy probable que tengan un impacto futuro en el negocio? / Has the Company identified the sources of disruptions caused by the COVID-19 crisis that have impacted or are very likely to have a future impact on the business?','','','Covid2'),
(1003,'1','NORMAL','3','¿Su equipo de Gestión de Riesgos Corporativos ha finalizado su análisis de la exposición de la Compañía al virus?; De ser así, favor compartir las conclusiones de este análisis. / Has your Enterprise Risk Management team completed its analysis of the Companys exposure to the virus?; If so, please share the conclusions of this analysis.','','','Covid3'),
(1004,'1','DES','4','Revisión General del Plan de Continuidad de Negocios (PCN)-Business Continuity Plan (BCP) General Review','','',''),
(1005,'1','SUB','a','¿Qué procedimientos se siguen si se confirma que un colaborador ha contraído el COVID-19? / What procedures are followed if an employee is confirmed to have contracted COVID-19?','','1004','Covid4a'),
(1006,'1','SUB','b','¿Se han realizado estudios y proyecciones de los principales clientes que pueden verse afectados por la crisis del coronavirus y cómo esta situación puede afectar la demanda y las ventas de su Compañía? / Have you conducted studies and projections of the main customers that may be affected by the coronavirus crisis and how this situation may affect the demand and sales of your Company?','','1004','Covid4b'),
(1007,'1','SUB','c','¿El Plan de Continuidad de Negocio está funcionando como se esperaba?; ¿La Compañía ha experimentado problemas en los sistemas de tecnología de la información (IT) durante este período de continuidad de negocio?; ¿Las Operaciones pueden seguir funcionando a completa capacidad durante esta fase? / Is the Business Continuity Plan working as expected?; Has the Company experienced information technology (IT) systems problems during this business continuity period?; Can Operations continue to function at full capacity during this phase?','','1004','Covid4c'),
(1008,'1','SUB','d','¿Su Compañía tiene contratada una póliza de Seguros de Incendio y Líneas Aliadas que incluya la cobertura de Lucro Cesante? / Does your Company have a Fire and Allied Lines Insurance policy that includes coverage for Loss of Profit?','','1004','Covid4d'),

(1009,'1','DES','','Problemas de dependencia y en la cadena de suministro y desafíos en la cadena de distribución de la Compañía. / Dependency and supply chain issues and challenges in the Companys distribution chain.','','',''),
(1010,'1','NORMAL','5','¿Su Compañía ha experimentado o espera experimentar problemas en la cadena de suministro y distribución?; ¿Su Compañía debe salir a ver a los clientes para suministrarles los servicios para los que fueron contratados? / Has your Company experienced or does it expect to experience problems in the supply and distribution chain?; Does your Company have to go out to customers to provide them with the services for which they were contracted?','','1009','Covid5'),
(1011,'1','NORMAL','6','Si se espera que las fuentes de suministro de la Compañía sufran algún impacto, ¿cuál es el resultado del análisis de los niveles actuales de existencias disponibles y su capacidad para atender a la demanda de los clientes? / If the Companys sources of supply are expected to be impacted, what is the result of the analysis of current stock levels on hand and their ability to meet customer demand?','','1009','Covid6'),

(1012,'1','DES','','Reduction in the demand for products/services.','','',''),
(1013,'1','NORMAL','7','¿Qué impacto anticipan en su resultado financiero?; ¿Ya se ha registrado impacto alguno a la fecha?; ¿Este impacto ha sido divulgado a los accionistas? / What impact do you anticipate on your financial results, and has there been any impact to date, and has this impact been disclosed to shareholders?','','1012','Covid7'),
(1014,'1','NORMAL','8','¿La Compañía espera experimentar alguna dificultad para honrar sus compromisos de deuda en los próximos 12 a 18 meses debido a la disrupciones generadas por esta crisis? / Does the Company expect to experience any difficulty in honoring its debt commitments in the next 12 to 18 months due to the disruption generated by this crisis?','','1012','Covid8'),
(1015,'1','NORMAL','9','¿Qué tipo de cláusulas de flexibilidad en los compromisos de pago tiene implementada en los contratos de deuda debido al potencial desplome en sus ingresos y/o EBITDA? / What kind of flexibility clause in the payment commitments have you implemented in the debt contracts due to the potential slump in your revenues and/or EBITDA?','','1012','Covid9'),
(1016,'1','NORMAL','10','¿Se esperan deficiencias (en existencias o de otro tipo)? / Are deficiencies (stock or otherwise) expected?','','1012','Covid10'),
(1017,'1','NORMAL','11','¿La Compañía ha llevado a cabo pruebas de presión financiera en respuesta a la crisis generada por el COVID-19 y el impacto potencial en el largo plazo?; ¿Cuáles son las conclusiones de estas pruebas? / Has the Company conducted financial stress tests in response to the crisis generated by COVID-19 and the potential long-term impact?; What are the conclusions of these tests?','','1012','Covid11'),
(1018,'1','NORMAL','12','¿Se espera un impacto material adverso en el flujo de caja y liquidez de la Compañía? / Is a material adverse impact on the Companys cash flow and liquidity expected?','','1012','Covid12'),
(1019,'1','NORMAL','13','¿Se espera un impacto material adverso en la condición financiera de su Compañía/organización o en los resultados operacionales como consecuencia de la pandemia del coronavirus? / Is a material adverse impact on your Companys/organizations financial condition or operating results expected as a result of the coronavirus pandemic?','','1012','Covid13'),
(1020,'1','NORMAL','14','¿Se han efectuado pruebas de presión relacionadas con la pérdida de beneficios como consecuencia del COVID-19?; ¿Qué conclusiones arrojan estos estudios? (Por ejemplo, ¿cuáles son las pérdidas máximas que la Compañía puede asumir en 12 meses sin exceder sus líneas de crédito)? / Have pressure tests related to the loss of profits as a result of COVID-19 been conducted (e.g., what are the maximum losses that the Company can assume in 12 months without exceeding its credit lines)?','','1012','Covid14'),
(1021,'1','NORMAL','15','¿Cómo va a cambiar los ingresos de la Compañía a partir del 01 de marzo del 2020 hacia fines de este año y cómo se comparan estos con los ingresos del mismo periodo del año pasado? / How will the Companys revenues change from March 1, 2020 towards the end of this year and how do they compare with the revenues of the same period last year?','','1012','Covid15'),
(1022,'1','NORMAL','16','¿Cómo ha impactado el COVID-19 en la proyección de los resultados financieros de la Compañía o si se planea tener algún cambio?; ¿Se han revisado estas proyecciones? / How has COVID-19 impacted the projection of the Companys financial results or if any changes are planned? Have these projections been reviewed?','','1012','Covid16'),
(1023,'1','NORMAL','17','¿Qué comunicados públicos se han efectuado informando de los cambios en estas proyecciones a los accionistas y al público en general?; ¿Cuándo fueron hechos públicos estos comunicados?; ¿Se nos puede proporcionar copia de estos comunicados? / What public announcements have been made informing shareholders and the general public of changes in these projections?; When were these announcements made public?; Can we be provided with copies of these announcements?','','1012','Covid17'),
(1024,'1','NORMAL','18','¿Su Compañía considera que está cumpliendo con los lineamientos de divulgación de información impuestos por la Comisión del Mercado de Valores de EE.UU. - SEC (si cotizan en alguna bolsa de dicho país) o la Superintendencia del Mercado de Valores - SMV o se necesita implementar alguna modificación para alinearse estos requerimientos?; ¿Se está utilizando los servicios de especialistas para asesorar a la Compañía en la regularización de esta situación? / Does your Company consider that it is complying with the disclosure guidelines imposed by the U.S. Securities and Exchange Commission (SEC) (if listed on a U.S. stock exchange) or the Superintendencia del Mercado de Valores (SMV) or does it need to implement any modifications to align with these requirements?; Are you using the services of specialists to advise the Company in regularizing this situation?','','1012','Covid18'),
(1025,'1','NORMAL','19','¿La Compañía ha solicitado al SEC y/o SMV según aplique alguna prórroga en el plazo de presentación de los estados financieros auditados? / Has the Company applied to the SEC and/or SMV, as applicable, for any extension of the deadline for filing the audited financial statements?','','1012','Covid19'),
(1026,'1','NORMAL','20','Si las acciones o papeles de deuda de la Compañía cotizan en bolsa de valores, ¿se ha contratado los servicios externos para asesorar a su Compañía para redactar los comunicados públicos de divulgación de información? / If the Companys stock or debt securities are publicly traded, have outside services been retained to advise your Company in drafting public disclosure communications?','','1012','Covid20'),

(1027,'1','DES','','Personal','','',''),
(1028,'1','NORMAL','21','¿Se han revisado y actualizado los procedimientos de salud y seguridad ocupacional a la luz del COVID-19? / Have occupational health and safety procedures been reviewed and updated in light of COVID-19?','','1027','Covid21'),
(1029,'1','NORMAL','22','¿La mayoría de sus colaboradores trabaja desde casa?; Sí o no, ¿se les ha proporcionado equipos de protección personal tales como mascarillas y guantes?; ¿Se ha implementado la política de distanciamiento social? (Es decir que haya una distancia mínima de 2 metros entre personas). ¿La Compañía hace obligatorio a su personal a que asista a trabajar a la oficina cuando no es posible trabajar remotamente desde casa? / Do most of your employees work from home?; Yes or no, have they been provided with personal protective equipment such as masks and gloves?; Has the social distancing policy been implemented (i.e. a minimum distance of 2 meters between people)? (i.e. a minimum distance of 2 meters between people). Does the Company make it mandatory for your staff to come to work at the office when it is not possible to work remotely from home?','','1027','Covid22'),
(1030,'1','NORMAL','23','¿La Compañía tiene algún plan para reducir operaciones en caso el declive económico continúe teniendo impactos negativos en la Compañía lo que incluye reducción de personal, cierre de oficinas o incluso un plan de paralización de operaciones? / Does the Company have any plans to reduce operations in case the economic downturn continues to have negative impacts on the Company, including staff reductions, office closures or even a plan to cease operations?','','1027','Covid23'),

(1031,'1','DES','','Riesgos Cibernéticos','','',''),
(1032,'1','NORMAL','24','¿Está la Compañía adecuadamente preparada y en capacidad de acomodar a sus colaboradores para que trabajen remotamente desde casa, particularmente en lo que se refiere a las funciones y los controles de los sistemas informáticos de la Compañía? / Is the Company adequately prepared and able to accommodate its employees to work remotely from home, particularly with regard to the functions and controls of the Companys IT systems?','','1031','Covid24'),
(1033,'1','NORMAL','25','¿Su Compañía contrata Seguros de Riesgos Cibernéticos (Cyber Risks)? / Does your Company take out Cyber Risks Insurance?','','1031','Covid25'),
(1034,'1','NORMAL','26','¿Qué planes tiene la Compañía para combatir el incremento en la ciber-delincuencia debido al acceso remoto de los colaboradores (si aplica), incluyendo vulneraciones de la seguridad de los sistemas informáticos y filtración de información de la Compañía a través de los dispositivos de acceso remoto de los colaboradores? / What plans does the Company have to combat the increase in cyber-crime due to remote access by employees (if applicable), including security breaches of IT systems and leakage of Company information through employees remote access devices?','','1031','Covid26');
 