	INSERT INTO INSURANCEPOLICY (IDINSURANCE, NAMEINSURANCE, CREATEDAT, UPDATEDAT, STATUS, DESCRIPTION) VALUES (1,'BBB ','2024-09-19','','ACTIVE','Poliza BBB');
	INSERT INTO INSURANCEPOLICY (IDINSURANCE, NAMEINSURANCE, CREATEDAT, UPDATEDAT, STATUS, DESCRIPTION) VALUES (2,'CYBER ','2024-09-19','','ACTIVE','Poliza CYBER');
	INSERT INTO INSURANCEPOLICY (IDINSURANCE, NAMEINSURANCE, CREATEDAT, UPDATEDAT, STATUS, DESCRIPTION) VALUES (3, 'D&O ','2024-09-19','','ACTIVE','Poliza D&O');
	INSERT INTO INSURANCEPOLICY (IDINSURANCE, NAMEINSURANCE, CREATEDAT, UPDATEDAT, STATUS, DESCRIPTION) VALUES (4, 'Property ','2024-09-19','','ACTIVE','Poliza Property Multiriesgos');
    INSERT INTO INSURANCEPOLICY (IDINSURANCE, NAMEINSURANCE, CREATEDAT, UPDATEDAT, STATUS, DESCRIPTION) VALUES (5, 'Responsabilidad Civil ','2024-09-19','','ACTIVE','Responsabilidad Civil');
