INSERT INTO questionary (questionary_id, policy_id, questionary_name, description, created_at, questionary_status,
                         source_file, total_number)
VALUES ('3', '1', 'CUESTIONARIO DE RESPONSABILIDAD CIVIL PROFESIONAL PARA ENTIDADES FINANCIERAS',
        'CUESTIONARIO PI', '', 'TRUE', 'CUESTIONARIOPI.docx', 83);

INSERT INTO question (question_id, questionary_id, question_type, description, question_text, question_json, parent_id,
                      document_id)
VALUES (3001, '3', 'NORMAL', '1',
        'Nombre de la Sociedad Principal y Domicilio Social. (Name of the Company and address):', '', '', 'companyName'),

       (3002, '3', 'NORMAL', '2', 'Fecha de constitución de la Sociedad Principal. (Date of constitution):', '', '',
        'companyEstablishmentDate'),

       (3003, '3', 'DES', '3', 'Descripción completa de la actividad. (Full Description of the activity):', '', '', ''),
       (3004, '3', 'SUB', 'a', 'Sociedad Principal. (Main Company):',
        '{"S1P3A":{"Id":"S1P3A","text":"","code":"mainCompanyActivity"}}', '3003', ''),
       (3005, '3', 'TABLE', 'b', 'Subsidiarias. (Subsidiaries):',
        '',
        '3003', 'subsidiariesTable'),

       (3006, '3', 'SELECTOR-NORMAL', '4', '¿Es la Compañía? (Is the company?)',
        '{ "S1P4A":{"Id":"S1P4A","text":"","code":"privateCompany"}}', '', ''),
       (3007, '3', 'DES', '',
        'En caso de cotizar en bolsa, por favor confirmar la(s) Bolsa(s) de Valores en que se cotizan. (If the company is public, please specify the stock exchange(s) on which they are listed):',
        '', '3006', 'stockExchanges'),

       (3008, '3', 'TABLE', '5', 'Detalles de cualquier accionista de la sociedad con más del 5%:',
        '',
        '', 'shareholdersTable'),

       (3009, '3', 'OPTIONAL', '6',
        '¿En los últimos 5 años, ha tenido lugar cualquier absorción, fusión, adquisición o cambio de control? (In the past 5 years, has there any acquisition, merger, take-over, etc?)',
        '{ "S1P6":{"Id":"S1P6","text":"","code":"acquisitionYes"}}', '', ''),

       (3010, '3', 'DES', '7', 'Información de Empleados. (Employees Information)', '', '', ''),
       (3011, '3', 'DES', 'a',
        'Indique el número de empleados bajo las siguientes categorías. (State number of employees in following categories):',
        '{ "S1P7R1":{"Id":"S1P7R1","text":"Año Actual(Current Year)"},"S1P7R2":{"Id":"S1P7R2","text":"Año anterior (Previous year)"}}',
        '3010', ''),
	   (3012, '3', 'MULTIPLE', 'i',
				'Número de empleados, incluyendo empleados temporales. (Number of employees, including temporary staff):',
				'{"S1P7A1R1":{"Id":"S1P7A1R1","text":"Año Actual (Current Year)","code":"currentYearTotalEmployees"},"S1P7A1R2":{"Id":"S1P7A1R2","text":"Año anterior (Previous year)","code":"previousYearTotalEmployees"}}', 
				'3011', ''),
	   (3013, '3', 'MULTIPLE', 'ii', 
				'Número de empleados de Capacitación. (Number of Personnel/Training staff):',
				'{"S1P7A2R1":{"Id":"S1P7A2R1","text":"Año Actual (Current Year)","code":"currentYearTrainingStaff"},"S1P7A2R2":{"Id":"S1P7A2R2","text":"Año anterior (Previous year)","code":"previousYearTrainingStaff"}}', 
				'3011', ''),

	   (3014, '3', 'MULTIPLE', 'iii',
				'Número de Personal en el Departamento de Auditoría Interna o de Cumplimiento. (Compliance Department and internal audit staff):',
				'{"S1P7A3R1":{"Id":"S1P7A3R1","text":"Año Actual (Current Year)","code":"currentYearComplianceStaff"},"S1P7A3R2":{"Id":"S1P7A3R2","text":"Año anterior (Previous year)","code":"previousYearComplianceStaff"}}', 
				'3011', ''),
	   (3015, '3', 'MULTIPLE', 'iv', 
				'Directores y Oficiales. (Directors & Officers):',
				'{"S1P7A4R1":{"Id":"S1P7A4R1","text":"Año Actual (Current Year)","code":"currentYearDirectors"},"S1P7A4R2":{"Id":"S1P7A4R2","text":"Año anterior (Previous year)","code":"previousYearDirectors"}}', 
				'3011', ''),
	   (3016, '3', 'MULTIPLE', 'v',
				'Personal de ventas, empleados profesionales o cualquier empleado directamente en contacto con personas ajenas a la organización. (Sales staff, Professional Staff or any employees directly involved with third parties.):',
				'{"S1P7A5R1":{"Id":"S1P7A5R1","text":"Año Actual (Current Year)","code":"currentYearSalesStaff"},"S1P7A5R2":{"Id":"S1P7A5R2","text":"Año anterior (Previous year)","code":"previousYearSalesStaff"}}', 
				'3011', ''),
	   (3017, '3', 'MULTIPLE', 'vi', 
				'Empleados de soporte. (Support Staff):',
				'{"S1P7A6R1":{"Id":"S1P7A6R1","text":"Año Actual (Current Year)","code":"currentYearSupportStaff"},"S1P7A6R2":{"Id":"S1P7A6R2","text":"Año anterior (Previous year)","code":"previousYearSupportStaff"}}', 
				'3011', ''),
       (3018, '3', 'TABLE', 'b',
        'Indique los nombres de todos los Directores y detalles sobre lo siguiente. (State names of all Executive Directors, including details of the following):',
        '',
        '3010', 'directorsTable'),

       (3019, '3', 'DES', 'c',
        '¿Cuál ha sido el porcentaje de rotación en las siguientes categorías de empleo, durante los últimos doce (12) meses? (What has been the percentage turnover in the following employment categories during the last twelve months?)',
        '{ "S1P7CR1":{"Id":"S1P7CR1","text":"Ingresos(Inward)"},"S1P7CR2":{"Id":"S1P7CR2","text":"Retiros(Outward)"}}',
        '3010', ''),
       (3020, '3', 'MULTIPLE', '',
        'Directores (incluyendo aquellos en las subsidiarias). Directors (including those of subsidiaries).',
        '{ "S1P7C1R1":{"Id":"S1P7C1R1","text":"Ingresos (Inward)","code":"directorsInwardTurnover"},"S1P7C1R2":{"Id":"S1P7C1R2","text":"Retiros (Outward)","code":"directorsOutwardTurnover"}}',
        '3019', ''),
       (3021, '3', 'MULTIPLE', '', 'Otros Empleados. (other employees) ',
        '{ "S1P7C2R1":{"Id":"S1P7C2R1","text":"Ingresos (Inward)","code":"otherEmployeesInwardTurnover"},"S1P7C2R2":{"Id":"S1P7C2R2","text":"Retiros (Outward)","code":"otherEmployeesOutwardTurnover"}}',
        '3019', ''),
       (3022, '3', 'SUB', 'd',
        'Indique el total de salarios pago a Directores y Empleados (incluyendo comisiones), durante el último año fiscal. (State the total of salaries, including commissions, paid to Directors and Employees during the last financial year:',
        '{ "S1P7DR1":{"Id":"S1P7DR1","text":"","code":"totalSalaries"}}', '3010', ''),

       (3023, '3', 'DES', '8', 'Actividades y Servicios de la Compañía. (Activities and Services of the Company):', '',
        '', ''),
       (3024, '3', 'DES', 'a',
        '¿Cuál es el porcentaje aproximado de ingresos de la Compañía proveniente de las siguientes actividades y servicios? (What percentage of the Proposers total revenues was derived from the following activities and services?)',
        '', '3023', ''),
      (3026, '3', 'MULTIPLE', '', 
        'Préstamos, arriendos o Extensiones de Crédito. (Loans, Leases or Extensions of Credit):',
        '{"S1P8A1R1":{"Id":"S1P8A1R1","text":"Año Actual (Current Year)","code":"currentYearLoans"},"S1P8A1R2":{"Id":"S1P8A1R2","text":"Año anterior (Previous year)","code":"previousYearLoans"}}', 
        '3024', ''),
		(3027, '3', 'MULTIPLE', 'i', 
				'Comercial. (Commercial):',
				'{"S1P8A2R1":{"Id":"S1P8A2R1","text":"Año Actual (Current Year)","code":"currentYearCommercialLoans"},"S1P8A2R2":{"Id":"S1P8A2R2","text":"Año anterior (Previous year)","code":"previousYearCommercialLoans"}}',
				'3024', ''),
		(3028, '3', 'MULTIPLE', 'ii', 
				'Interbanco. (Interbank):',
				'{"S1P8A3R1":{"Id":"S1P8A3R1","text":"Año Actual (Current Year)","code":"currentYearInterbancaLoans"},"S1P8A3R2":{"Id":"S1P8A3R2","text":"Año anterior (Previous year)","code":"previousYearInterbancaLoans"}}',
				'3024', ''),
		(3029, '3', 'MULTIPLE', 'iii', 
				'Personal. (Personal):',
				'{"S1P8A4R1":{"Id":"S1P8A4R1","text":"Año Actual (Current Year)","code":"currentYearPersonalLoans"},"S1P8A4R2":{"Id":"S1P8A4R2","text":"Año anterior (Previous year)","code":"previousYearPersonalLoans"}}', 
				'3024', ''),
		(3030, '3', 'MULTIPLE', '', 
				'Financiamiento Comercial. (Trade Financing, Forfait):',
				'{"S1P8A5R1":{"Id":"S1P8A5R1","text":"Año Actual (Current Year)","code":"currentYearTradeFinancing"},"S1P8A5R2":{"Id":"S1P8A5R2","text":"Año anterior (Previous year)","code":"previousYearTradeFinancing"}}', 
				'3024', ''),
		(3031, '3', 'MULTIPLE', '', 
				'Negociaciones de Cambio. (Foreign Exchange Dealings):',
				'{"S1P8A6R1":{"Id":"S1P8A6R1","text":"Año Actual (Current Year)","code":"currentYearForeignExchange"},"S1P8A6R2":{"Id":"S1P8A6R2","text":"Año anterior (Previous year)","code":"previousYearForeignExchange"}}',
				'3024', ''),
		(3032, '3', 'MULTIPLE', '', 
				'Negociaciones de Mercado. (Commodity Market Dealings):',
				'{"S1P8A7R1":{"Id":"S1P8A7R1","text":"Año Actual (Current Year)","code":"currentYearCommodityMarket"},"S1P8A7R2":{"Id":"S1P8A7R2","text":"Año anterior (Previous year)","code":"previousYearCommodityMarket"}}',
				'3024', ''),
		(3033, '3', 'MULTIPLE', '', 
				'Actuando como Negociador/Corredor de Títulos. (Acting as Securities Broker/Dealer):',
				'{"S1P8A8R1":{"Id":"S1P8A8R1","text":"Año Actual (Current Year)","code":"currentYearSecuritiesBroker"},"S1P8A8R2":{"Id":"S1P8A8R2","text":"Año anterior (Previous year)","code":"previousYearSecuritiesBroker"}}',
				'3024', ''),
		(3034, '3', 'MULTIPLE', '',
				'Actuando como depositario o custodio o agente de Títulos o dinero. (Acting as a custodian or depository or managing agent for Securities or money).',
				'{"S1P8A9R1":{"Id":"S1P8A9R1","text":"Año Actual (Current Year)","code":"currentYearCustodian"},"S1P8A9R2":{"Id":"S1P8A9R2","text":"Año anterior (Previous year)","code":"previousYearCustodian"}}', 
				'3024', ''),
		(3035, '3', 'MULTIPLE', 'i',
				'Actuando como un Asesor para. (Acting as an advisor for) / 1.Fusiones y adquisiciones. (Mergers and Acquisitions):',
				'{"S1P8A10R1":{"Id":"S1P8A10R1","text":"Año Actual (Current Year)","code":"currentYearMergers"},"S1P8A10R2":{"Id":"S1P8A10R2","text":"Año anterior (Previous year)","code":"previousYearMergers"}}', 
				'3024', ''),
		(3036, '3', 'MULTIPLE', 'ii', 
				'Colocación de Acciones y Nuevas Emisiones. (Share Placing and New Issues):',
				'{"S1P8A11R1":{"Id":"S1P8A11R1","text":"Año Actual (Current Year)","code":"currentYearSharePlacing"},"S1P8A11R2":{"Id":"S1P8A11R2","text":"Año anterior (Previous year)","code":"previousYearSharePlacing"}}', 
				'3024', ''),
		(3037, '3', 'MULTIPLE', 'iii', 
				'Riesgo de capital. (Venture Capital):',
				'{"S1P8A12R1":{"Id":"S1P8A12R1","text":"Año Actual (Current Year)","code":"currentVentureCapital"},"S1P8A12R2":{"Id":"S1P8A12R2","text":"Año anterior (Previous year)","code":"previousVentureCapital"}}', 
				'3024', ''),
		(3038, '3', 'MULTIPLE', 'iv', 
				'Otra (por favor describa) / Other (please describe):',
				'{"S1P8A13R1":{"Id":"S1P8A13R1","text":"Año Actual (Current Year)","code":"otherActivities"},"S1P8A13R2":{"Id":"S1P8A13R2","text":"Año anterior (Previous year)","code":"previousOtherActivities"}}', 
				'3024', ''),
		(3039, '3', 'MULTIPLE', '',
				'Actuando como fideicomisario bajo contrato. (Acting as a trustee under bond indenture):',
				'{"S1P8A14R1":{"Id":"S1P8A14R1","text":"Año Actual (Current Year)","code":"currentYearTrustee"},"S1P8A14R2":{"Id":"S1P8A14R2","text":"Año anterior (Previous year)","code":"previousYearTrustee"}}', 
				'3024', ''),
		(3040, '3', 'MULTIPLE', '',
				'Asesorías en el extranjero (si aplica, anexe un papel detallando cuales países están cubiertos). (Overseas Advisory (if applicable, attach separate sheet stating which countries are covered.))',
				'{"S1P8A15R1":{"Id":"S1P8A15R1","text":"Año Actual (Current Year)","code":"currentYearOverseasAdvisory"},"S1P8A15R2":{"Id":"S1P8A15R2","text":"Año anterior (Previous year)","code":"previousYearOverseasAdvisory"}}',
				'3024', ''),
		(3041, '3', 'MULTIPLE', '', 
				'Otras Actividades. (Other Activities):',
				'{"S1P8A16R1":{"Id":"S1P8A16R1","text":"Año Actual (Current Year)","code":"currentYearOtherActivities"},"S1P8A16R2":{"Id":"S1P8A16R2","text":"Año anterior (Previous year)","code":"previousYearOtherActivities"}}',
				'3024', ''),
       (3042, '3', 'OPTIONAL', 'b',
        '¿Ha la Compañía ofrecido algún nuevo servicio a sus clientes en los pasados tres (3) años? (Has the Company offered any new services to its clients during the last 3 years?)',
        '{"S1P8B":{"Id":"S1P8B","text":"","code":"newServicesYes"}}', '3023', ''),
       (3043, '3', 'OPTIONAL', 'c',
        '¿Tiene la Compañía la intención de ofrecer algún nuevo servicio para sus clientes dentro de los próximos doce (12) meses? (Does the Company intend to offer any new services to its clients during the next 12 months?)',
        '{"S1P8C":{"Id":"S1P8C","text":"","code":"futureServicesYes"}}', '3023', ''),
       (3044, '3', 'SUB', 'd',
        '¿Ante que organismo regulador debe rendir cuentas la Compañía y sus subsidiarias? (To which regulatory authorities are the Company and its subsidiaries accountable?) ',
        '{"S1P8D":{"Id":"S1P8D","text":"","code":"regulatoryAuthorities"}}', '3023', ''),
       (3045, '3', 'OPTIONAL', 'e',
        '¿Ha la Compañía estado actuando como asesor en procesos de Fusiones y Adquisiciones en los últimos doce (12) meses? (Has the Company been acting as an adviser in regards to Merger & Acquisitions Activities? )',
        '{"S1P8E":{"Id":"S1P8E","text":"","code":"mergerAdvisorYes"}}', '3023', ''),
       (3046, '3', 'TABLE', '',
        'Si la respuesta es SÍ, favor complete lo siguiente. (If yes, please complete the following): ',
        '',
        '3045', 'mergerAdvisorTable'),
       (3047, '3', 'OPTIONAL', 'f',
        'Ha la Compañía estado actuando como asesor en procesos de Colocación de Acciones y Nuevas Emisiones en los últimos doce (12) meses? (Has the Company been acting as an adviser in regards to Share Placing and New Issues?) ',
        '{"S1P8F":{"Id":"S1P8F","text":"","code":"sharePlacingAdvisorYes"}}', '3023', ''),
       (3048, '3', 'DES', '',
        'Si la respuesta es SÍ, favor complete lo siguiente. (If yes, please complete the following): ', '', '3047',
        ''),

       (3049, '3', 'OPTIONAL', '9',
        '¿La Compañía realiza actividades de fideicomiso o de manejo de fondos de inversión? (Does the Company undertake trust activities or fund investment management? )',
        '{"S1P10":{"Id":"S1P10","text":"","code":"trustActivitiesYes"}}', '', ''),
       (3050, '3', 'DES', '',
        'Si la respuesta es SÍ, favor complete el Anexo No. 1. (If yes, please complete the Annex N.1): ', '', '3049', ''),

       (3051, '3', 'OPTIONAL', '10',
        '¿La Compañía realiza actividades de fideicomiso o de manejo de fondos de inversión? (Does the Company undertake trust activities or fund investment management? )',
        '{"S1P11":{"Id":"S1P11","text":"","code":"electronicTransferYes"}}', '', ''),
       (3052, '3', 'DES', '',
        'Si la respuesta es SÍ, favor complete el Anexo No. 2. (If yes, please complete the Annex N.2):', '', '3051',
        ''),

       (3053, '3', 'OPTIONAL', '11',
        '¿Provee la Compañía facilidades de acceso por Internet? Does the Company provide an Internet Facility? ',
        '{"S1P12":{"Id":"S1P12","text":"","code":"internetAccessYes"}}', '', ''),
       (3054, '3', 'DES', '',
        'Si la respuesta es SÍ, favor complete el Anexo No. 3. (If yes, please complete the Annex N.3):', '', '3053',
        ''),

       (3055, '3', 'DES', '12', 'Detalles sobre Auditorías (Audits)', '', '', ''),
       (3056, '3', 'SUB', 'a',
        'Nombre y dirección de los Auditores Externos / (Name and address of External Auditors): ',
        '{"S1P13A":{"Id":"S1P13A","text":"","code":"externalAuditorName"}}', '3055', ''),
       (3057, '3', 'SUB', 'b',
        'Frecuencia de las auditorías a la Compañía por parte del Auditor Externo: (Frequency of Auditing Services to the Company performed by the Auditors) : ',
        '{"S1P13B":{"Id":"S1P13B","text":"","code":"auditFrequency"}}', '3055', ''),
       (3058, '3', 'OPTIONAL', 'c',
        '¿El Auditor Externo revisa regularmente los sistemas de control interno? (Does the External Auditor regularly review the system of internal controls?)',
        '{"S1P13C":{"Id":"S1P13C","text":"","code":"internalControlReviewYes"}}', '3055', ''),
       (3059, '3', 'OPTIONAL', 'd',
        '¿El Auditor Externo emite reportes escritos? (Does the External Auditor furnish written reports?)',
        '{"S1P13D":{"Id":"S1P13D","text":"","code":"writtenReportsYes"}}', '3055', ''),
       (3060, '3', 'OPTIONAL-NORMAL', 'e',
        '¿Se ha realizado alguna recomendación en las últimas dos auditorías? (Has the Auditing Firm made any recommendations in the last two audits?) / Si la respuesta es SÍ, favor dar detalles y confirmar ¿ si se han adoptado? (If yes, please give details and please confirm if they have been adopted)',
        '{"S1P13E":{"Id":"S1P13E","text":"","code":"auditRecommendationsYes"}}', '3055', ''),
       (3061, '3', 'OPTIONAL-NORMAL', 'f',
        '¿Se han cambiado de auditores externos en los últimos 5 años? (Has the Auditing Firm been changed in the last five(5) years?) / Si la respuesta es SÍ, por favor explique las razones. / (If so, give details and explain why the change was made).',
        '{"S1P13E2":{"Id":"S1P13E2","text":"","code":"auditorChangedYes"}}', '3055', ''),
       (3062, '3', 'OPTIONAL', 'g',
        '¿Tiene la Compañía un Departamento de Auditoría Interna? (Does the Company have an Internal Audit Department?)',
        '{"S1P13G":{"Id":"S1P13G","text":"","code":"internalAuditDeptYes"}}', '3055', ''),
       (3063, '3', 'SUB', 'h',
        'Frecuencia de las auditorías por el Auditor Interno. (Frequency of Auditing by the Audit Department):',
        '{"S1P13H":{"Id":"S1P13H","text":"","code":"internalAuditFrequency"}}', '3055', ''),
       (3064, '3', 'OPTIONAL', 'i',
        '¿Tiene la Compañía un Código de Ética por escrito que abarque a todos los empleados y que incluya los lineamientos de conducta aceptable, y con las normas para actividades externas aceptable, conflictos de intereses, regalos de clientes y prohibición de otros empleos? (Does the Company have a written Code of Ethics encompassing all employees which includes a statement on the principles of acceptable conduct, and with guidelines for acceptable outside activities, conflicts of interests, gifts from customers, and prohibition on other employment?)',
        '{"S1P13I":{"Id":"S1P13I","text":"","code":"ethicsCodeYes"}}', '3055', ''),
       (3065, '3', 'OPTIONAL', 'j',
        '¿Se requiere de los empleados una aceptación por escrito de que han leído el Código de Ética y de que se apegan a sus normas? (Are employees required to agree in writing that they have read the ethics code and are abiding by said code?)',
        '{"S1P13J":{"Id":"S1P13J","text":"","code":"ethicsCodeAcknowledgementYes"}}', '3055', ''),
       (3066, '3', 'OPTIONAL', 'k',
        '¿Requiere de todos los Directores y empleados una declaración de sus intereses de negocios externos, así como las relaciones que podrían conllevar a posibles conflictos de interés? (Do you require all Directors and Employees to declare their outside business interests and specify relationships which could lead to possible conflicts of interest?)',
        '{"S1P13K":{"Id":"S1P13K","text":"","code":"conflictDeclarationYes"}}', '3055', ''),

       (3067, '3', 'DES', '13', 'Departamento Legal/Abogados (Legal Department/Lawyers)',
        '{"S1P13K":{"Id":"S1P13K","text":"","code":"conflictDeclarationYes"}}', '', ''),
       (3068, '3', 'SUB', 'a',
        'Nombre y dirección de los de los asesores legales que actúan rutinariamente en nombre de la Compañía. (Name and address of Lawyers routinely acting for the Company): N/A',
        '{"S1P14A":{"Id":"S1P14A","text":"","code":"legalNameAddress"}}', '3067', ''),
       (3069, '3', 'OPTIONAL', 'b',
        '¿Proporcionan los abogados opiniones escritas acerca de la legalidad de cualquier cambio de política administrativa o de inversión o de fideicomiso en conexión con las actividades del Proponente? (Do the Lawyers supply written opinions as to the legality of any change in investment or management policy in connection with Trusteeship activities?)',
        '{"S1P14B":{"Id":"S1P14B","text":"","code":"legalOpinionsYes"}}', '3067', ''),
       (3070, '3', 'OPTIONAL', 'c',
        '¿Tiene el Proponente un Departamento Legal Interno? (Does the Proposer have an In-house Legal Department?) / Si la respuesta es SÍ, por favor dar detalles de / (If so, please give details of):',
        '{"S1P14C":{"Id":"S1P14C","text":"","code":"internalLegalDeptYes"}}', '3067', ''),
       (3071, '3', 'SUB', 'i',
        '¿Cuántas personas calificadas lo componen? (How many legally qualified individuals does it consist of?)',
        '{"S1P14C1":{"Id":"S1P14C1","text":"","code":"internalLegalIndividuals"}}', '3070', ''),
       (3072, '3', 'SUB', '',
        '¿Cuáles son las responsabilidades del Departamento? (What are the departments responsibilities?)',
        '{"S1P14C11":{"Id":"S1P14C11","text":"","code":"departmentResponsibilities"}}', '3070', ''),
       (3073, '3', 'OPTIONAL-NORMAL', 'ii',
        '¿Ofrece su servicio a terceras personas? Si la respuesta es SÍ, favor dar detalles. (Does it offer its services to customers or other Third Parties? If so, please give details.) ',
        '{"S1P14C11":{"Id":"S1P14C11","text":"","code":"thirdPartyServicesYes"}}', '3072', ''),
       (3074, '3', 'OPTIONAL', 'iii',
        '¿Son todas las publicaciones emitidas por la Compañía revisadas regularmente por el Departamento Legal Interno y/o asesores legales externos? (Are all publications issued by the Company reviewed by the In-house Legal Department and/or outside legal advisers?)',
        '{"S1P14C3":{"Id":"S1P14C3","text":"","code":"legalReviewYes"}}', '3072', ''),

       (3075, '3', 'DES', '14', 'RECLAMACIONES/SINIESTRALIDAD (Claims History) ', '', '', ''),
       (3076, '3', 'OPTIONAL', 'a',
        '¿Hay algún litigio, actualmente pendiente, en contra de la Compañía, sus subsidiarias, agencias; o cualquier de sus empleados que pueda afectar el seguro solicitado? (Is there any material litigation currently pending against the company, its subsidiaries, its branches or any employee that may affect the coverage for which you are applying for?) ',
        '{"S1P15A":{"Id":"S1P15A","text":"","code":"pendingLitigationYes"}}', '3075', ''),
       (3077, '3', 'OPTIONAL', 'b',
        '¿Tiene la Compañía algún conocimiento o información, después de una investigación completa, de cualquier hecho, error o circunstancia que pudiera dar cabida a reclamos en su contra o de sus subsidiarias o agencias a las cuales es aplicable esta solicitud? (Does the Company have any knowledge or information, after full enquiry, of any fact, error or circumstances whatsoever which might give rise to claims being made against it, its subsidiaries or any branches to which this application applies?) ',
        '{"S1P15B":{"Id":"S1P15B","text":"","code":"potentialClaimsYes"}}', '3075', ''),

        (3078, '3', 'OPTIONAL', 'c',
        '¿Ha la Compañía recibido críticas o directrices de algún órgano regulador durante los últimos cinco (5) años? / (During the last five years has the Company received any admonishment or critical directive from any regulatory authority?)',
        '{"S1P15C":{"Id":"S1P15C","text":"","code":"regulatoryCriticismYes"}}',
        '3075', ''),

        (3079, '3', 'SUB', '', 
        'En caso afirmativo a cualquier pregunta anterior, por favor dar detalles:(If the answer is YES to any of the questions above please give details):',
        '{"S1P15C1":{"Id":"S1P15C1","text":"","code":"claimDetails"}}',
        '3075', ''),

       (3080, '3', 'DES', '15', 'PROGRAMA DE SEGURO ANTERIOR O ACTUAL. (Previous/Current Insurance Program)', '', '',
        ''),
        
       (3081, '3', 'OPTIONAL', 'a',
        '¿Ha tenido la Compañía, durante los últimos tres (3) años, un Seguro de Responsabilidad Civil Profesional? (Have the Company contracted PI Insurance in the last 3 years?)',
        '{"S1P16":{"Id":"S1P16","text":"","code":"previousInsuranceYes"}}', '3080', ''),
       (3082, '3', 'SUB', '', 'Asegurador',
        '{"S1P16A1":{"Id":"S1P16A1","text":"","code":"previousInsurer"}}', '3080', ''),
       (3083, '3', 'SUB', '', 'Fecha de terminación de la póliza. (Expiry date of the policy):',
        '{"S1P16A2":{"Id":"S1P16A2","text":"","code":"policyEndDate"}}', '3080', ''),
       (3084, '3', 'SUB', '', 'Suma Asegurada. (Sum Insured): ',
        '{"S1P16A3":{"Id":"S1P16A3","text":"","code":"policyAssuredSum"}}', '3080', ''),
       (3085, '3', 'SUB', 'b', 'Suma asegurada requerida para esta propuesta: ',
        '{"S1P16B":{"Id":"S1P16B","text":"","code":"requestedAssuredSum"}}', '3080', '');


INSERT INTO question_option (question_id, option_text, created_at)
VALUES ('3006', 'Privada ~ No cotiza en Bolsa (Private) - ##Cotiza en Bolsa (Public)', ''),
       ('3005',
        'Nombre de la Subsidiaria (Name of the Subsidiary)-Ubicación (Location)-Fecha de Constitución (Date Established)-Servicios (Services)',
        ''),
       ('3008', 'Nombre (Name)-Porcentaje de Acciones (% of shares)', ''),
       ('3009', 'yes-no', ''),
       ('3018',
        'Nombre(Name)-Tiempo de Servicio(Length of Service)-Cargo (Position)-No. de Acciones en su propiedad(Number of own shares)',
        ''),
       ('3042', 'yes-no', ''),
       ('3043', 'yes-no', ''),
       ('3045', 'yes-no', ''),
       ('3046',
        'Oferente (Offerer)-Parte Interesada (Interested Party)-Resultados (Outcome)-Valor de la Oferta (Offer Value)',
        ''),
       ('3047', 'yes-no', ''),
       ('3049', 'yes-no', ''),
       ('3051', 'yes-no', ''),
       ('3053', 'yes-no', ''),
       ('3058', 'yes-no', ''),
       ('3059', 'yes-no', ''),
       ('3060', '##yes-no', ''),
       ('3061', '##yes-no', ''),
       ('3062', 'yes-no', ''),
       ('3064', 'yes-no', ''),
       ('3065', 'yes-no', ''),
       ('3066', 'yes-no', ''),
       ('3069', 'yes-no', ''),
       ('3070', 'yes-no', ''),
       ('3073', '##yes-no', ''),
       ('3074', 'yes-no', ''),
       ('3076', 'yes-no', ''),
       ('3077', 'yes-no', ''),
       ('3078', 'yes-no', ''),
       ('3081', 'yes-no', '');